### ISSUE TITLE
Tunnelblick not working on older macs with Sonoma 14.4.1 (OpenCore Patcher)

### ISSUE THREAD

**Issue by crogialli** [Tunnelblick/Tunnelblick#802] opened 2024-04-25 14:28 UTC
When tunnelblick is installed on older Macs supporting Ventura 14.4.1 via OpenCore Patcher, the main window "OpenVPN Details" is not accessible and tunnelblick hangs.

**To Reproduce**
Have a Mac booting with OpenCore Patcher and GeForce GTX 680 graphics (I have two).
Try to start the main window "OpenVPN details". The windows does not show up, the coloured spinner spins forever, Tunnelblick hangs.

**Expected behavior**
The "OpenVPN details" window appears

**Screenshots**
None significant

**Additional context**
I know this is an unsupported configuration. However, tunnelblick is the only known app to not work (OpenVpn Client works flawlessly, in example).

**Diagnostic info**
Please attach a file with the info obtained by following the instructions at [Before You Post About a Problem](https://tunnelblick.net/cBeforeYouPost.html)
Can't Access OpenVPN detail windows, so I can't upload standard bug report.
Here is what it reports in transcript when started from CLI:

2024-04-25 16:15:31.390 Tunnelblick[6567:73808] Tunnelblick: macOS 14.4.1; Tunnelblick 4.0.1 (build 5971)
2024-04-25 16:15:34.933 Tunnelblick[6567:73901] Cannot determine SIP status; assuming SIP is enabled. stdout from '/usr/bin/csrutil status' = 'System Integrity Protection status: unknown (Custom Configuration).

Configuration:
	Apple Internal: disabled
	Kext Signing: disabled
	Filesystem Protections: disabled
	Debugging Restrictions: enabled
	DTrace Restrictions: enabled
	NVRAM Protections: enabled
	BaseSystem Verification: enabled

This is an unsupported configuration, likely to break in the future and leave your machine in an unknown state.
'
2024-04-25 16:15:37.315 Tunnelblick[6567:73808] Sparkle: ===== Tunnelblick =====
2024-04-25 16:15:37.316 Tunnelblick[6567:73808] Sparkle: Verified appcast signature
2024-04-25 16:16:08.137 Tunnelblick[6567:73808] attributedStringFromHTML: initWithHTML failed
2024-04-25 16:16:08.579 Tunnelblick[6567:73808] attributedStringFromHTML: initWithHTML failed
2024-04-25 16:16:09.017 Tunnelblick[6567:73808] attributedStringFromHTML: initWithHTML failed
2024-04-25 16:16:19.484 Tunnelblick[6567:73808] attributedStringFromHTML: initWithHTML failed

**Comment by jkbullard** [comment] 2024-04-25 15:40
Duplicate of #762.

**Closed by jkbullard** 2024-04-25 15:40 UTC
