### ISSUE TITLE
Unable to set permissions error when up command given an executable

### ISSUE THREAD

**Issue by zaygraveyard** [Tunnelblick/Tunnelblick#814] opened 2024-08-13 21:43 UTC
**Describe the bug**
I get a "VPN Configuration Installation Error" when the config contains an up command with an executable instead of a script.

**To Reproduce**
1. Try to install a config with an `up` command with an executable, ex. `up "/bin/sh -c '/usr/sbin/ipconfig set $dev DHCP'"`
2. See error
```
Installation failed:

At line 141 of the OpenVPN configuration file: Unable to set permissions on '/private/var/folders/sk/fsvkfqk52z7d0mppbvjk30q00000gn/T/net.tunnelblick.tunnelblick-rIAcAJ/test.tblk/Contents/Resources/sh.sh'
```

**Expected behavior**
It works without errors.

**Additional context**
 - OS: macOS 14.5
 - Version `Tunnelblick 4.0.1 (build 5971)`

This issue seams related to #726 and the workaround suggested in https://github.com/Tunnelblick/Tunnelblick/issues/726#issuecomment-1149289926 works for this issue.

**Comment by jkbullard** [comment] 2024-08-14 14:52
@zaygraveyard - Thanks for reporting this.

The problem is that Tunnelblick expects the "command" to be a script, not an executable.

That will be fixed in the next beta release, with the following limitation: The executable must have an absolute path. So the following (your example) will install properly:

`up "/bin/sh -c '/usr/sbin/ipconfig set $dev DHCP'"`

But this still won't install properly, because sh is not an absolute path:

`up "sh -c '/usr/sbin/ipconfig set $dev DHCP'"`

(This issue will be closed automatically when the fix is committed publicly.)

**Comment by zaygraveyard** [comment] 2024-08-15 10:43
This limitation seems reasonable to me. 😄

**Closed** 2024-09-04 13:32 UTC
