### ISSUE TITLE
Failed to change owner & group on Tunnelblick.app to match Tunnelblick.app with authorization. 

### ISSUE THREAD

**Issue by machejc** [Tunnelblick/Tunnelblick#690] opened 2021-07-01 06:07 UTC
**Describe the bug**
Trying to upgrade Tunnelblick from Tunnelblick 3.8.6beta04 (build 5705) to Tunnelblick 3.8.6beta05 on macOS Big Sur 11.4 and get the following error message:

Failed to change owner & group on Tunnelblick.app to match Tunnelblick.app with authorization. 

**To Reproduce**
1. Upgrade from Tunnelblick 3.8.6beta04 (build 5705) to Tunnelblick 3.8.6beta05 on macOS Big Sur 11.4
2. Type in userid and password as requested. 
3. See error occur
4. Upgrade shuts down without upgrading
5. 
**Expected behavior**
I want to be able to upgrade Tunnelblick easily like I always have done

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.4
 - Browser: Chrome
 - Version: Version 91.0.4472.114 (Official Build) (x86_64)

**Comment by jkbullard** [comment] 2021-07-01 11:13
Duplicate of #687

**Closed by jkbullard** 2021-07-01 11:13 UTC
