### ISSUE TITLE
TMPDIR issue on 3.5.4

### ISSUE THREAD

**Issue by shyukri** [Tunnelblick/Tunnelblick#274] opened 2015-09-23 06:25 UTC
```
2015-09-23 09:21:39 *Tunnelblick: OS X 10.10.5; Tunnelblick 3.5.4 (build 4270.4395); prior version 3.5.3 (build 4270.4371)
Could not start OpenVPN (openvpnstart returned with status #173)
...........
Contents of the openvpnstart log:
*Tunnelblick: openvpnstart log:
     If present, the TMPDIR environment variable must be set to '/var/folders/z3/45tkgkc50ns76m7_dpfjhnr00000gn/T/'; it is '/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/'
     Complete environment = {
         "COMMAND_MODE" = unix2003;
         HOME = "/Users/mac_mini";
         LOGNAME = "mac_mini";
         PATH = "/usr/bin:/bin:/usr/sbin:/sbin";
         SHELL = "/bin/bash";
         TMPDIR = "/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/";
         USER = "mac_mini";
         "__CF_USER_TEXT_ENCODING" = "0x0:0:0";
     }
```
It was working fine in the previous version

**Comment by shyukri** [comment] 2015-09-23 06:30
After exit and restart of the app now it was able to connect.

**Comment by jkbullard** [comment] 2015-09-23 11:46
Tunnelblick detected that the TMPDIR environment variable had a value which was not the same as the value returned by the NSTemporaryDirectory() system function.

openvpnstart runs as root and may run bash scripts, so setting TMPDIR to somewhere unexpected could lead to corruption of arbitrary files.

This situation could indicate an attack, so Tunnelblick refuses to run its openvpnstart component.

This problem is unlikely to be specific to Tunnelblick 3.5.4 because nothing in the changes between 3.5.3 and 3.5.4 affect systems running OS X 10.5 or higher, and you are running 10.10.

I cannot reproduce this problem, so I would welcome more information:
  * When did this happen? For example, did it happen the first time you tried to launch Tunnelblick after updating? Or the first time you tried to connect a configuration after updating?
  * Can you describe any unusual activities between the time Tunnelblick was launched and the time the problem occurred? For example, did you switch users, or relaunch Finder, or do anything like that?
  * Is this a "connect when computer starts" configuration?
  * Is there anything unusual about your system? (Security software, etc.)

**Comment by jkbullard** [comment] 2015-10-23 08:50
I am closing this issue because it has been abandoned.

**Closed by jkbullard** 2015-10-23 08:50 UTC
