### ISSUE TITLE
This copy of Tunnelblick has been tampered with (the digital signature is invalid)?

### ISSUE THREAD

**Issue by jtv7** [Tunnelblick/Tunnelblick#331] opened 2016-09-11 16:15 UTC
After updating to the latest beta yesterday, when I restarted my computer today I received this message:

"This copy of Tunnelblick has been tampered with (the digital signature is invalid).  Please check with the provider of this copy of Tunnelblick before using it"

What could be causing this?

**Comment by jkbullard** [comment] 2016-09-11 17:03
It could be caused by a number of things.

What version of OS X are you using?

To see more specifically what the problem is, you can enter the following command in Terminal:

`sudo codesign -v -v --deep /Applications/Tunnelblick.app`

(You'll need to enter an admin password and press the Enter/Return key. "sudo" is required because some versions of OS X make certain files in applications unavailable except to root.) You should see output like this:

`/Applications/Tunnelblick.app: valid on disk`
`/Applications/Tunnelblick.app: satisfies its Designated Requirement`

Have you tried downgrading to the latest stable version, then updating back to the latest stable version? (You can do this on the Preferences panel of Tunnelblick's 'VPN Details' window. Un-check "Check for updates to beta versions", click "Check Now" and downgrade to 3.6.6. Then put a check back in the checkbox, click "Check Now", and update to the latest beta.

Or just downloading a fresh copy and installing it (you won't lose any settings)?

**Comment by jtv7** [comment] 2016-09-11 17:32
I get the output you specified when running the command.  After I received this error, I downloaded a fresh beta copy from the Tunnelblock website, restarted my computer, and this issue happened again.

Also, I ran this command: `codesign --display --verbose=4 /Applications/Tunnelblick.app`  before and after the re-install and the output is the same.  I would prefer to stay on the beta if possible.

**Comment by jkbullard** [comment] 2016-09-11 17:35
What version of OS X are you using?

**Comment by jtv7** [comment] 2016-09-11 17:36
OS X El Capitan 10.11.6

**Comment by jkbullard** [comment] 2016-09-11 17:38
Please check the Console log (/Applications/Utilities/Console "All Messages") to see what shows up when you launch Tunnelblick.

**Comment by jtv7** [comment] 2016-09-11 17:47
The issues appears to only happen when I restart.  I get this in the console: 

```
9/11/16 12:44:20.755 PM Tunnelblick[719]: Tunnelblick: OS X 10.11.6; Tunnelblick 3.6.7beta04 (build 4601)
9/11/16 12:44:26.589 PM Tunnelblick[719]: runTunnelblickd: no data available from tunnelblickd socket; sleeping 5.000000 seconds...
9/11/16 12:44:31.589 PM Tunnelblick[719]: runTunnelblickd: no data available from tunnelblickd socket; sleeping 5.000000 seconds...
9/11/16 12:44:36.589 PM Tunnelblick[719]: runTunnelblickd: no data available from tunnelblickd socket; sleeping 5.000000 seconds...
9/11/16 12:44:41.589 PM Tunnelblick[719]: runTunnelblickd: no data available from tunnelblickd socket; sleeping 5.000000 seconds...
9/11/16 12:44:46.590 PM Tunnelblick[719]: runTunnelblickd: no data available from tunnelblickd socket; sleeping 5.000000 seconds...
9/11/16 12:44:51.590 PM Tunnelblick[719]: runTunnelblickd: tunnelblickd is not responding; received only 0 bytes
9/11/16 12:44:51.591 PM Tunnelblick[719]: tunnelblickd status from checkSignature: -1
```

When I start manually (from /Applications) I get:

```
9/11/16 12:47:28.326 PM Tunnelblick[788]: Tunnelblick: OS X 10.11.6; Tunnelblick 3.6.7beta04 (build 4601)
9/11/16 12:47:29.305 PM Tunnelblick[788]: Set program update feedURL to https://www.tunnelblick.net/appcast-b.rss
9/11/16 12:47:30.425 PM Tunnelblick[788]: Sparkle: ===== Tunnelblick.app =====
9/11/16 12:47:30.425 PM Tunnelblick[788]: Sparkle: Verified appcast signature
```

**Comment by jkbullard** [comment] 2016-09-11 17:51
Only when you restart -- so if you restart your computer and get the error, close the warning dialog, and launch Tunnelblick by double-clicking it in /Applications everything is OK?

**Comment by jtv7** [comment] 2016-09-11 17:53
Yes.  I click "Quit" at the dialog (instead of continue).  I then go to /Applications and launch, and the dialog does not show.

**Comment by jkbullard** [comment] 2016-09-11 18:10
OK, thanks. Then you don't need to worry, your copy of Tunnelblick is fine.

I think what is happening is that you probably have your computer log you in automatically when you start it when you restart your computer, and/or there is a lot for the system to do and/or you have a slow computer or hard drive, and/or are low on memory, or something like that. So when OS X starts Tunnelblick, OS X hasn't finished fully initializing, and in particular it hasn't set up "tunnelblickd", which is a background program that performs privileged operations for the Tunnelblick application. So when the Tunnelblick application asks "tunnelblickd" to check the application's signature, tunnelblickd never responds (because it wasn't running when the application made the request). Since the application never gets a "signature is OK" response, it puts up the warning message.

Does that make sense to you? Could you turn off "automatic login" temporarily, restart, and then wait to log in for say, two minutes, to let OS X finish starting up everything? Then when you login, Tunnelblick should be able to check the signature without a problem. If you can confirm that that works, I can probably figure out a way to fix this problem. I will be creating a new beta in the next few days, and I'd love to include such a fix.

(Tunnelblick's check of the signature changed in 3.6.7beta04; previously the check was not usually done by root. But OS X Sierra requires that it be done by root, so the new beta usually does it by root.)

**Comment by jtv7** [comment] 2016-09-11 18:28
I believe I have automatic login disabled because I have FileVault encryption enabled.  Your logic seems right though, as my computer takes about 3-4 minutes to be fully ready to go.  I will try logging in as a guest to see if that works.

**Comment by jkbullard** [comment] 2016-09-11 18:34
Ah. "3-4 minutes to be fully ready to go" -- then what I described makes sense. Instead of logging in as guest (which probably won't have Tunnelblick start at login and thus might not show the problem), please restart your computer, and then just wait, say, 5 minutes before logging in your as your normal user. If Tunnelblick starts without complaining at that point, then the cause is as I described.

Thanks for reporting this, and for helping figure out what is happening!

**Comment by jtv7** [comment] 2016-09-11 18:48
I will try it on a virtual machine I have, because with FileVault I am prompted to login as soon as the computer turns on (not boots up, turns on).  I will report back.  

Thanks for your help with this issue and your contributions to the overall project!

**Comment by jtv7** [comment] 2016-09-11 19:20
Ok, so I can't seem to replicate the issue in the VM.  However, in the Console I see one line of `9/11/16 2:14:35.220 PM Tunnelblick[355]: runTunnelblickd: no data available from tunnelblickd socket; sleeping 5.000000 seconds...
`
On my machine with the issue, I had that multiple times, followed by `tunnelblickd is not responding; received only 0 bytes`.  So I would agree that `tunnelblickd` isn't being started in time, just as you suspected.

Feel free to close this issue, and thank you for your help.

**Comment by jkbullard** [comment] 2016-09-11 19:31
OK, thanks for the update. This is the first report I've had of this, but there only a few thousand people who are using the latest beta (which is less than 24 hours old), and probably most of them haven't restarted their computer or don't have it as heavily loaded as you do, so the problem wouldn't show up for them.

I'll leave this issue open until I do something about this problem.

Thanks again for reporting this.

**Comment by jkbullard** [comment] 2016-09-11 20:55
@jtv7 (and others):

I have created a fix for this (I hope!) Anyone who would like to test it should contact developers@tunnelblick.net for a link.

**Comment by jkbullard** [comment] 2016-09-13 15:55
I have created a new version of Tunnelblick with a _different_ fix for this problem, which I believe is a better approach. Contact developers@tunnelblick.net for a link to the new version.

**Comment by jkbullard** [comment] 2016-09-16 01:20
Tunnelblick 3.6.7 and 3.6.8beta02 fix this problem.

**Closed by jkbullard** 2016-09-16 01:20 UTC

**Comment by rubin55** [comment] 2017-11-30 08:51
I just ran into this using Tunnelblick current stable (3.7.4a) With High Sierra. I just had a critical security patch applied and after reboot, I get this consistently. Note that starting the app from Applications or rebooting does not fix it. 

Reinstalling Tunnelblick did fix it but it is a little worrisome..

**Comment by jkbullard** [comment] 2017-11-30 14:23
@rubin55 - Thanks for your report  (and sorry for the problem).

What "critical security patch" was applied? You can get that from the "Updates" panel of the App Store.

The only recent one I have is "Security Update 2017-001" (the version is blank). I didn't have this problem, either after installing the update or after restarting my computer after that. (The update didn't require a restart, I just wanted to check that a restart wasn't part of the problem.)

Interestingly, the first restart after the update showed two screens that appear after installing macOS: a "send Apple info" window and the "Setting up your account..." animated window.)

**Comment by rubin55** [comment] 2017-11-30 18:22
The patch was for the passwordless root issue as documented here:https://www.wired.com/story/macos-high-sierra-hack-root/. I just got a notification in the right-upper corner telling me to restart. My macOS version is 10.13.1. I also don't see a newer patch than Security Update 2017-001, but I'm sure I applied that one earlier.. I think.

**Comment by agreensh** [comment] 2018-08-20 19:48
I have just had this on High Sierra with Tunnelblick 3.7.6a (build 5080)
