### ISSUE TITLE
IPv6 TLS negotiation fails; IPv4 fallback after timeout works

### ISSUE THREAD

**Issue by hirschferkel** [Tunnelblick/Tunnelblick#781] opened 2023-12-10 13:53 UTC
Since update to version 3.8.8. I suffer a connecting lag, as the first try will end in an TLS handshake fail, but every second handshake will work. My NAS will always connect on first try within 5 seconds, with the same VPN, so it is definitely a problem of Tunnelblick.

It worked for 1 years without any changes in VPN and Tunnelblick.
Connection is stable all time, no interruptions while connected.

**To Reproduce**
Connect to a stored VPN over Tunnelblick.

It will be caused with any first try. It will always work after 1 minute, when Tunnelblick will try to connect a second time, automatically.

**Expected behavior**
Connection on first try and establish it within 5 seconds instead of 1 Minute lag.

**Error log**
```
2023-12-10 14:43:25.593802 MANAGEMENT: >STATE:1702215805,WAIT,,,,,,
2023-12-10 14:43:32.514682 TCP/UDP: Incoming packet rejected from [AF_INET6]::ffff:XXX:1196[30], expected peer address: [AF_INET6]2003:ef:2f00:XXX:1196 (allow this incoming source address/port by removing --remote or adding --float)
2023-12-10 14:44:23.506116 or from peer address: [AF_INET]XXXX:1196
2023-12-10 14:44:25.869776 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
2023-12-10 14:44:25.869884 TLS Error: TLS handshake failed
2023-12-10 14:44:25.870213 SIGUSR1[soft,tls-error] received, process restarting
2023-12-10 14:44:25.870254 MANAGEMENT: >STATE:1702215865,RECONNECTING,tls-error,,,,,
...

2023-12-10 14:44:27.191255 TLS: Initial packet from [AF_INET]84.185.109.142:1196, sid=faf1c48c 3a1b6621
2023-12-10 14:44:27.345403 VERIFY OK: depth=1, C=TW, ST=Taiwan, L=Taipei, O=Synology Inc., OU=Certificate Authority, CN=Synology Inc. CA, emailAddress=product@synology.com
2023-12-10 14:44:27.345754 VERIFY OK: depth=0, C=TW, ST=Taiwan, L=Taipei, O=Synology Inc., OU=FTP Team, CN=synology.com, emailAddress=product@synology.com
```

**Comment by jkbullard** [comment] 2023-12-10 15:14
@hirschferkel - Thanks for your report.

Please post the diagnostic info obtained by following the instructions at [Read Before You Post](https://tunnelblick.net/cBeforeYouPost.html). If you prefer, you can email it to developers@tunnelblick.net.

**Comment by hirschferkel** [comment] 2023-12-10 15:25
@jkbullard 
```
*Tunnelblick: macOS 12.7.1 (21G920); Tunnelblick 4.0.0beta13 (build 5930); prior version 3.8.8g (build 5779.3); Admin user
git commit 2971256b064c71cd1e0dff684281963c277c64d8
The Tunnelblick.app process is not being translated (x86_64)
System Integrity Protection is enabled
Model: MacBookPro11,5

================================================================================

Configuration VPNConfig sysad

Sanitized" condensed configuration file for /Users//Library/Application Support/Tunnelblick/Configurations/VPNConfig sysad.tblk:

dev tun
tls-client
remote intern.NameOfNetwork.de 1196
pull
proto udp
script-security 2
reneg-sec 0
cipher AES-256-CBC
auth SHA512
auth-user-pass
<ca>
[Security-related line(s) omitted]
</ca>

================================================================================

Files in VPNConfig sysad.tblk:
      Contents/Resources/config.ovpn

================================================================================

Configuration preferences:

-doNotReconnectOnFastUserSwitch = 1
-doNotReconnectOnWakeFromSleep = 1
-routeAllTrafficThroughVpn = 0
-keychainHasUsernameAndPassword = 1
-loginWindowSecurityTokenCheckboxIsChecked = 0
-lastConnectionSucceeded = 1

================================================================================

Wildcard preferences:


================================================================================

Program preferences:

skipWarningThatIPANotFetchedBeforeConnection = 1
skipWarningThatIPAddressDidNotChangeAfterConnection = 1
skipWarningAboutPreAuthorizedActivity = 1
skipWarningAboutPlacingIconNearTheSpotlightIcon = 1
skipWarningAboutDnsProblems = 1
skipWarningAboutNotCheckingIPAddressChanges = 1
buildExpirationTimestamp = 1587392106
placeIconInStandardPositionInStatusBar = 1
launchAtNextLogin = 1
notOKToCheckThatIPAddressDidNotChangeAfterConnection = 0
tunnelblickVersionHistory = (
    "4.0.0beta13 (build 5930)",
    "3.8.8g (build 5779.3)",
    "3.8.8f (build 5779.2)",
    "3.8.8g (build 5779.3)",
    "3.8.8f (build 5779.2)",
    "3.8.8e (build 5779.1)",
    "3.8.8d (build 5779)",
    "3.8.8c (build 5778)",
    "3.8.8b (build 5777)",
    "3.8.8a (build 5776)"
)
statusDisplayNumber = 0
lastLaunchTime = 723914098.095242
showConnectedDurations = 1
lastLanguageAtLaunchWasRTL = 0
connectionWindowDisplayCriteria = showWhenConnecting
maxLogDisplaySize = 102400
lastConnectedDisplayName = VPNConfig sysad
keyboardShortcutIndex = 1
updateCheckAutomatically = 1
NSWindow Frame ConnectingWindow = 765 718 389 217 0 0 1920 1175 
NSWindow Frame SUStatusFrame = 760 780 400 135 0 0 1920 1175 
NSWindow Frame SUUpdateAlert = 650 587 620 392 0 0 1920 1175 
NSWindow Frame ListingWindow = 1047 218 633 710 0 0 1680 1027 
detailsWindowFrameVersion = 5930
detailsWindowFrame = {{968, 642}, {920, 522}}
detailsWindowLeftFrame = {{0, 0}, {167, 402}}
detailsWindowViewIndex = 0
detailsWindowConfigurationsTabIdentifier = log
leftNavOutlineViewExpandedDisplayNames = (
    "ALT/"
)
leftNavSelectedDisplayName = VPNConfig sysad
AdvancedWindowTabIdentifier = vpnCredentials
haveDealtWithOldTunTapPreferences = 1
haveDealtWithAlwaysShowLoginWindow = 1
haveDealtWithOldLoginItem = 1
haveDealtWithAfterDisconnect = 1
SUEnableAutomaticChecks = 1
SUFeedURL = https://www.tunnelblick.net/appcast-s.rss
SUScheduledCheckInterval = 86400
SUSendProfileInfo = 0
SULastCheckTime = 2023-12-10 15:14:58 +0000
SUHasLaunchedBefore = 1
askedUserIfOKToCheckThatIPAddressDidNotChangeAfterConnection = 1
buildExpirationTimestamp = 1587392106
haveDealtWithSparkle1dot5b6 = 1
updateSendProfileInfo = 0

================================================================================

Forced preferences:

(None)

================================================================================

Deployed forced preferences:

(None)

================================================================================

Tunnelblick Kext Policy Data:



================================================================================

Tunnelblick Log:

2023-12-10 16:15:01.783937 *Tunnelblick: macOS 12.7.1 (21G920); Tunnelblick 4.0.0beta13 (build 5930); prior version 3.8.8g (build 5779.3)
2023-12-10 16:15:02.069874 *Tunnelblick: Cannot recognize the VPNConfig sysad-loadTap preference value of '(null)', so Tunnelblick will not load the tap kext
2023-12-10 16:15:02.072698 *Tunnelblick: Attempting connection with VPNConfig sysad using shadow copy; Set nameserver = 0x00000301; monitoring connection
2023-12-10 16:15:02.073131 *Tunnelblick: openvpnstart start VPNConfig\ sysad.tblk 60950 0x00000301 0 1 0 0x0210c130 -ptADGNWradsgnw 2.5.9-openssl-1.1.1w <password>
2023-12-10 16:15:02.087905 *Tunnelblick: openvpnstart starting OpenVPN
2023-12-10 16:15:02.625154 DEPRECATED OPTION: --cipher set to 'AES-256-CBC' but missing in --data-ciphers (AES-256-GCM:AES-128-GCM). Future OpenVPN version will ignore --cipher for cipher negotiations. Add 'AES-256-CBC' to --data-ciphers or change --cipher 'AES-256-CBC' to --data-ciphers-fallback 'AES-256-CBC' to silence this warning.
2023-12-10 16:15:02.625973 OpenVPN 2.5.9 x86_64-apple-darwin [SSL (OpenSSL)] [LZO] [LZ4] [PKCS11] [MH/RECVDA] [AEAD] built on Nov 21 2023
2023-12-10 16:15:02.626004 library versions: OpenSSL 1.1.1w  11 Sep 2023, LZO 2.10
2023-12-10 16:15:02.627731 MANAGEMENT: TCP Socket listening on [AF_INET]127.0.0.1:60950
2023-12-10 16:15:02.627787 Need hold release from management interface, waiting...
2023-12-10 16:15:03.338500 *Tunnelblick: openvpnstart log:
     OpenVPN started successfully.
     Command used to start OpenVPN (one argument per displayed line):
          /Applications/Tunnelblick.app/Contents/Resources/openvpn/openvpn-2.5.9-openssl-1.1.1w/openvpn
          --daemon
          --log-append /Library/Application Support/Tunnelblick/Logs/-SUsers-S-SLibrary-SApplication Support-STunnelblick-SConfigurations-SVPNConfig sysad.tblk-SContents-SResources-Sconfig.ovpn.769_0_1_0_34652464.60950.openvpn.log
          --cd /Library/Application Support/Tunnelblick/Users//VPNConfig sysad.tblk/Contents/Resources
          --machine-readable-output
          --setenv IV_GUI_VER "net.tunnelblick.tunnelblick 5930 4.0.0beta13 (build 5930)"
          --verb 3
          --config /Library/Application Support/Tunnelblick/Users//VPNConfig sysad.tblk/Contents/Resources/config.ovpn
          --setenv TUNNELBLICK_CONFIG_FOLDER /Library/Application Support/Tunnelblick/Users//VPNConfig sysad.tblk/Contents/Resources
          --verb 3
          --cd /Library/Application Support/Tunnelblick/Users//VPNConfig sysad.tblk/Contents/Resources
          --management 127.0.0.1 60950 /Library/Application Support/Tunnelblick/Mips/VPNConfig sysad.tblk.mip
          --setenv IV_SSO webauth
          --management-query-passwords
          --management-hold
          --script-security 2
          --route-up /Applications/Tunnelblick.app/Contents/Resources/client.up.tunnelblick.sh -9 -d -f -m -w -ptADGNWradsgnw
          --down /Applications/Tunnelblick.app/Contents/Resources/client.down.tunnelblick.sh -9 -d -f -m -w -ptADGNWradsgnw
2023-12-10 16:15:03.340500 MANAGEMENT: Client connected from [AF_INET]127.0.0.1:60950
2023-12-10 16:15:03.356057 MANAGEMENT: CMD 'pid'
2023-12-10 16:15:03.356110 MANAGEMENT: CMD 'auth-retry interact'
2023-12-10 16:15:03.356143 MANAGEMENT: CMD 'state on'
2023-12-10 16:15:03.356186 MANAGEMENT: CMD 'state'
2023-12-10 16:15:03.356222 MANAGEMENT: CMD 'bytecount 1'
2023-12-10 16:15:03.356229 *Tunnelblick: Established communication with OpenVPN
2023-12-10 16:15:03.363815 *Tunnelblick: >INFO:OpenVPN Management Interface Version 3 -- type 'help' for more info
2023-12-10 16:15:03.364288 MANAGEMENT: CMD 'hold release'
2023-12-10 16:15:03.370144 *Tunnelblick: Obtained VPN username and password from the Keychain
2023-12-10 16:15:03.370887 MANAGEMENT: CMD 'username "Auth" "sysadNameOfNetwork"'
2023-12-10 16:15:03.412750 MANAGEMENT: CMD 'password [...]'
2023-12-10 16:15:03.413558 WARNING: No server certificate verification method has been enabled.  See http://openvpn.net/howto.html#mitm for more info.
2023-12-10 16:15:03.413599 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
2023-12-10 16:15:03.419493 MANAGEMENT: >STATE:1702221303,RESOLVE,,,,,,
2023-12-10 16:15:03.616112 TCP/UDP: Preserving recently used remote address: [AF_INET6]SomeAddress:1196
2023-12-10 16:15:03.616234 Socket Buffers: R=[786896->786896] S=[9216->9216]
2023-12-10 16:15:03.616259 setsockopt(IPV6_V6ONLY=0)
2023-12-10 16:15:03.616313 UDP link local (bound): [AF_INET6][undef]:1194
2023-12-10 16:15:03.616345 UDP link remote: [AF_INET6]SomeAddress:1196
2023-12-10 16:15:03.616452 MANAGEMENT: >STATE:1702221303,WAIT,,,,,,
2023-12-10 16:16:03.620646 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
2023-12-10 16:16:03.620737 TLS Error: TLS handshake failed
2023-12-10 16:16:03.621176 SIGUSR1[soft,tls-error] received, process restarting
2023-12-10 16:16:03.621210 MANAGEMENT: >STATE:1702221363,RECONNECTING,tls-error,,,,,
2023-12-10 16:16:03.621995 MANAGEMENT: CMD 'hold release'
2023-12-10 16:16:03.622077 WARNING: No server certificate verification method has been enabled.  See http://openvpn.net/howto.html#mitm for more info.
2023-12-10 16:16:03.622100 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
2023-12-10 16:16:03.623148 TCP/UDP: Preserving recently used remote address: [AF_INET]IP-Adress:1196
2023-12-10 16:16:03.623331 Socket Buffers: R=[786896->786896] S=[9216->9216]
2023-12-10 16:16:03.623485 UDP link local (bound): [AF_INET][undef]:1194
2023-12-10 16:16:03.623551 UDP link remote: [AF_INET]IP-Adress:1196
2023-12-10 16:16:03.623647 MANAGEMENT: >STATE:1702221363,WAIT,,,,,,
2023-12-10 16:16:03.624191 MANAGEMENT: CMD 'hold release'
2023-12-10 16:16:03.654162 MANAGEMENT: >STATE:1702221363,AUTH,,,,,,
2023-12-10 16:16:03.654227 TLS: Initial packet from [AF_INET]IP-Adress:1196, sid=5442aeb2 8647eb81
2023-12-10 16:16:03.654418 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
2023-12-10 16:16:03.809034 VERIFY OK: depth=1, C=TW, ST=Taiwan, L=Taipei, O=Synology Inc., OU=Certificate Authority, CN=Synology Inc. CA, emailAddress=product@synology.com
2023-12-10 16:16:03.809436 VERIFY OK: depth=0, C=TW, ST=Taiwan, L=Taipei, O=Synology Inc., OU=FTP Team, CN=synology.com, emailAddress=product@synology.com
2023-12-10 16:16:04.491977 Control Channel: TLSv1.2, cipher TLSv1.2 DHE-RSA-AES256-GCM-SHA384, peer certificate: 1024 bit RSA, signature: RSA-SHA1
2023-12-10 16:16:04.492183 [synology.com] Peer Connection Initiated with [AF_INET]IP-Adress:1196
2023-12-10 16:16:05.795001 MANAGEMENT: >STATE:1702221365,GET_CONFIG,,,,,,
2023-12-10 16:16:05.795146 SENT CONTROL [synology.com]: 'PUSH_REQUEST' (status=1)
2023-12-10 16:16:05.819276 PUSH: Received control message: 'PUSH_REPLY,route 192.168.1.0 255.255.255.0,route 10.8.0.0 255.255.255.0,route 10.8.0.1,topology net30,ping 10,ping-restart 60,ifconfig 10.8.0.10 10.8.0.9'
2023-12-10 16:16:05.819455 OPTIONS IMPORT: timers and/or timeouts modified
2023-12-10 16:16:05.819475 OPTIONS IMPORT: --ifconfig/up options modified
2023-12-10 16:16:05.819481 OPTIONS IMPORT: route options modified
2023-12-10 16:16:05.819489 Using peer cipher 'AES-256-CBC'
2023-12-10 16:16:05.819572 Outgoing Data Channel: Cipher 'AES-256-CBC' initialized with 256 bit key
2023-12-10 16:16:05.819585 Outgoing Data Channel: Using 512 bit message hash 'SHA512' for HMAC authentication
2023-12-10 16:16:05.819606 Incoming Data Channel: Cipher 'AES-256-CBC' initialized with 256 bit key
2023-12-10 16:16:05.819615 Incoming Data Channel: Using 512 bit message hash 'SHA512' for HMAC authentication
2023-12-10 16:16:05.820098 Opened utun device utun3
2023-12-10 16:16:05.820193 MANAGEMENT: >STATE:1702221365,ASSIGN_IP,,10.8.0.10,,,,
2023-12-10 16:16:05.820308 /sbin/ifconfig utun3 delete
                           ifconfig: ioctl (SIOCDIFADDR): Can't assign requested address
2023-12-10 16:16:05.836043 NOTE: Tried to delete pre-existing tun/tap instance -- No Problem if failure
2023-12-10 16:16:05.836087 /sbin/ifconfig utun3 10.8.0.10 10.8.0.9 mtu 1500 netmask 255.255.255.255 up
2023-12-10 16:16:05.839232 MANAGEMENT: >STATE:1702221365,ADD_ROUTES,,,,,,
2023-12-10 16:16:05.839269 /sbin/route add -net 192.168.1.0 10.8.0.9 255.255.255.0
                           add net 192.168.1.0: gateway 10.8.0.9
2023-12-10 16:16:05.844282 /sbin/route add -net 10.8.0.0 10.8.0.9 255.255.255.0
                           add net 10.8.0.0: gateway 10.8.0.9
2023-12-10 16:16:05.846091 /sbin/route add -net 10.8.0.1 10.8.0.9 255.255.255.255
                           add net 10.8.0.1: gateway 10.8.0.9
                           16:16:05 *Tunnelblick:  **********************************************
                           16:16:05 *Tunnelblick:  Start of output from client.up.tunnelblick.sh
                           16:16:07 *Tunnelblick:  NOTE: No network configuration changes need to be made.
                           16:16:07 *Tunnelblick:  WARNING: Will NOT monitor for other network configuration changes.
                           16:16:07 *Tunnelblick:  WARNING: Will NOT disable IPv6 settings.
                           16:16:08 *Tunnelblick:  DNS servers '192.168.178.1 DNS-Server DNS-Server' will be used for DNS queries when the VPN is active
                           16:16:08 *Tunnelblick:  NOTE: The DNS servers do not include any free public DNS servers known to Tunnelblick. This may cause DNS queries to fail or be intercepted or falsified even if they are directed through the VPN. Specify only known public DNS servers or DNS servers located on the VPN network to avoid such problems.
                           16:16:08 *Tunnelblick:  Flushed the DNS cache via dscacheutil
                           16:16:08 *Tunnelblick:  /usr/sbin/discoveryutil not present. Not flushing the DNS cache via discoveryutil
                           16:16:08 *Tunnelblick:  Notified mDNSResponder that the DNS cache was flushed
                           16:16:08 *Tunnelblick:  Not notifying mDNSResponderHelper that the DNS cache was flushed because it is not running
                           16:16:08 *Tunnelblick:  End of output from client.up.tunnelblick.sh
                           16:16:08 *Tunnelblick:  **********************************************
2023-12-10 16:16:08.129881 Initialization Sequence Completed
2023-12-10 16:16:08.129926 MANAGEMENT: >STATE:1702221368,CONNECTED,SUCCESS,10.8.0.10,IP-Adress,1196,,
2023-12-10 16:16:09.245041 *Tunnelblick: Warning: Could not obtain a list of DNS addresses that are expected
2023-12-10 16:16:09.353584 *Tunnelblick: Routing info stdout:
   route to: 192.168.178.1
destination: 192.168.178.1
  interface: en0
      flags: <UP,HOST,DONE,LLINFO,WASCLONED,IFSCOPE,IFREF,ROUTER>
 recvpipe  sendpipe  ssthresh  rtt,msec    rttvar  hopcount      mtu     expire
       0         0         0        10         8         0      1500      1190 
stderr:

2023-12-10 16:16:09.354315 *Tunnelblick: Warning: DNS server address 192.168.178.1 is not a public IP address and is not being routed through the VPN.


2023-12-10 16:16:09.459637 *Tunnelblick: Routing info stdout:
   route to: DNS-Server
destination: DNS-Server
  interface: en0
      flags: <UP,HOST,DONE,LLINFO,WASCLONED,IFSCOPE,IFREF>
 recvpipe  sendpipe  ssthresh  rtt,msec    rttvar  hopcount      mtu     expire
       0         0         0         0         0         0      1500         0 
stderr:

2023-12-10 16:16:09.460174 *Tunnelblick: Warning: DNS server address DNS-Server is not a public DNS server known to Tunnelblick and is not being routed through the VPN
2023-12-10 16:16:09.565415 *Tunnelblick: Routing info stdout:
   route to: DNS-Server
destination: ::
       mask: default
    gateway: fe80::9a9b:cbff:fe6a:f803%en0
  interface: en0
      flags: <UP,GATEWAY,DONE,PRCLONING,GLOBAL>
 recvpipe  sendpipe  ssthresh  rtt,msec    rttvar  hopcount      mtu     expire
       0         0         0         0         0         0      1500         0 
stderr:

2023-12-10 16:16:09.565882 *Tunnelblick: Warning: DNS server address DNS-Server is not a public IP address and is not being routed through the VPN.


2023-12-10 16:16:14.708467 *Tunnelblick: This computer's apparent public IP address (95.88.94.93) was unchanged after the connection was made

================================================================================

Installer log:

Tunnelblick installer started 2023-12-10 14:32:31.131329; getuid() = 503; geteuid() = 0; getgid() = 20; getegid() = 20
currentDirectoryPath = '/'; 1 arguments:
     0x0003
Determined username '' from getuid(): 503
renamex_np() tests succeeded for /Applications
renamex_np() tests succeeded for /Library/Application Support/Tunnelblick
renamex_np() tests succeeded for /Users//Library/Application Support/Tunnelblick/Configurations
Moved /Applications/Tunnelblick.app to the Trash
Copied /Volumes/Tunnelblick/Tunnelblick.app to /Applications/Tunnelblick.app
Removed any 'com.apple.quarantine' extended attributes
Changed ownership of /Applications/Tunnelblick.app and its contents from 501:80 to 0:0
Need to replace and/or reload 'tunnelblickd':
    daemonHashesMatch  = NO
    plistHashesMatch   = YES
    activePlistMatches = YES
Replaced /Library/LaunchDaemons/net.tunnelblick.tunnelblick.tunnelblickd.plist
Used launchctl to load tunnelblickd
Tunnelblick installer succeeded

================================================================================

Down log:

15:38:59 *Tunnelblick:  **********************************************
15:38:59 *Tunnelblick:  Start of output from client.down.tunnelblick.sh
15:39:00 *Tunnelblick:  WARNING: Not restoring network settings because no saved Tunnelblick DNS information was found.
15:39:00 *Tunnelblick:  Flushed the DNS cache with dscacheutil -flushcache
15:39:00 *Tunnelblick:  Notified mDNSResponder that the DNS cache was flushed
15:39:00 *Tunnelblick:  End of output from client.down.tunnelblick.sh
15:39:00 *Tunnelblick:  **********************************************

================================================================================

Previous down log:

14:43:17 *Tunnelblick:  **********************************************
14:43:17 *Tunnelblick:  Start of output from client.down.tunnelblick.sh
14:43:18 *Tunnelblick:  WARNING: Not restoring network settings because no saved Tunnelblick DNS information was found.
14:43:18 *Tunnelblick:  Flushed the DNS cache with dscacheutil -flushcache
14:43:18 *Tunnelblick:  Notified mDNSResponder that the DNS cache was flushed
14:43:18 *Tunnelblick:  End of output from client.down.tunnelblick.sh
14:43:18 *Tunnelblick:  **********************************************

================================================================================

Network services:

An asterisk (*) denotes that a network service is disabled.
iPhone USB
Thunderbolt Ethernet
Wi-Fi
OPNSense NameOfNetwork
VPN (Cisco IPSec)

Wi-Fi Power (en0): On

================================================================================

ifconfig output:

lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> mtu 16384
	options=1203<RXCSUM,TXCSUM,TXSTATUS,SW_TIMESTAMP>
	inet 127.0.0.1 netmask 0xff000000 
	inet6 ::1 prefixlen 128 
	inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1 
	nd6 options=201<PERFORMNUD,DAD>
gif0: flags=8010<POINTOPOINT,MULTICAST> mtu 1280
stf0: flags=0<> mtu 1280
en0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=400<CHANNEL_IO>
	ether f4:5c:89:ac:e1:27 
	inet6 fe80::1033:e1f9:8d4b:4d8c%en0 prefixlen 64 secured scopeid 0x4 
	inet6 2a02:8109:aba3:d000:d5:7f58:4318:be2f prefixlen 64 autoconf secured 
	inet6 2a02:8109:aba3:d000:919d:5122:3158:598 prefixlen 64 autoconf temporary 
	inet 192.168.178.26 netmask 0xffffff00 broadcast 192.168.178.255
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect
	status: active
en2: flags=8963<UP,BROADCAST,SMART,RUNNING,PROMISC,SIMPLEX,MULTICAST> mtu 1500
	options=460<TSO4,TSO6,CHANNEL_IO>
	ether 82:17:07:44:ef:41 
	media: autoselect <full-duplex>
	status: inactive
en1: flags=8963<UP,BROADCAST,SMART,RUNNING,PROMISC,SIMPLEX,MULTICAST> mtu 1500
	options=460<TSO4,TSO6,CHANNEL_IO>
	ether 82:17:07:44:ef:40 
	media: autoselect <full-duplex>
	status: inactive
bridge0: flags=8822<BROADCAST,SMART,SIMPLEX,MULTICAST> mtu 1500
	options=63<RXCSUM,TXCSUM,TSO4,TSO6>
	ether 82:17:07:44:ef:40 
	Configuration:
		id 0:0:0:0:0:0 priority 0 hellotime 0 fwddelay 0
		maxage 0 holdcnt 0 proto stp maxaddr 100 timeout 1200
		root id 0:0:0:0:0:0 priority 0 ifcost 0 port 0
		ipfilter disabled flags 0x0
	member: en1 flags=3<LEARNING,DISCOVER>
	        ifmaxaddr 0 port 6 priority 0 path cost 0
	member: en2 flags=3<LEARNING,DISCOVER>
	        ifmaxaddr 0 port 5 priority 0 path cost 0
	media: <unknown type>
	status: inactive
p2p0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> mtu 2304
	options=400<CHANNEL_IO>
	ether 06:5c:89:ac:e1:27 
	media: autoselect
	status: inactive
awdl0: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> mtu 1484
	options=400<CHANNEL_IO>
	ether 4e:0a:34:0a:f7:2c 
	inet6 fe80::4c0a:34ff:fe0a:f72c%awdl0 prefixlen 64 scopeid 0x9 
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect
	status: active
llw0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=400<CHANNEL_IO>
	ether 4e:0a:34:0a:f7:2c 
	inet6 fe80::4c0a:34ff:fe0a:f72c%llw0 prefixlen 64 scopeid 0xa 
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect
	status: active
utun0: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1380
	inet6 fe80::b2cf:2652:7f31:c53d%utun0 prefixlen 64 scopeid 0xb 
	nd6 options=201<PERFORMNUD,DAD>
utun1: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 2000
	inet6 fe80::54bc:a2a6:1924:89d%utun1 prefixlen 64 scopeid 0xc 
	nd6 options=201<PERFORMNUD,DAD>
utun2: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1000
	inet6 fe80::ce81:b1c:bd2c:69e%utun2 prefixlen 64 scopeid 0xd 
	nd6 options=201<PERFORMNUD,DAD>
utun3: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1500
	inet 10.8.0.10 --> 10.8.0.9 netmask 0xffffffff 

================================================================================

Non-Apple kexts that are loaded:

Index Refs Address            Size       Wired      Name (Version) UUID <Linked Against>
  167    0 0xffffff7f9a4aa000 0x3000     0x3000     com.bitgapp.eqMac2Driver (2.0) C8E2C7F3-989B-3EF0-AE56-80D339AC2703 <137 7 6 3>
  168    0 0xffffff7f9a4af000 0x4000     0x4000     com.shinywhitebox.iShowU-Audio-Capture (1.0.5) 38B2277C-7B00-3E65-938C-39B338FD7616 <137 7 6 3>
  182    0 0xffffff7f9a4b5000 0x40000    0x40000    com.paragon-software.filesystems.ntfs (329.9.15) 16EAB37B-E3F8-3237-86AB-FD06378198CF <9 7 6 1>

================================================================================

Quit Log:

2023-12-10 16:05:55.706824 applicationShouldTerminate: termination because of logout; delayed until 'shutdownTunnelblick' finishes)
2023-12-10 16:05:55.714354 shutDownTunnelblick: started.
2023-12-10 16:05:55.714987 shutDownTunnelblick: Starting cleanup.
2023-12-10 16:05:55.715538 cleanup: Entering cleanup
2023-12-10 16:05:55.726096 synchronized user defaults
2023-12-10 16:06:01.547135 shutDownTunnelblick: Cleanup finished.
2023-12-10 16:06:01.579310 Finished shutting down Tunnelblick; allowing termination

================================================================================

Traces Log:


================================================================================

Console Log:
```

**Comment by jkbullard** [comment] 2023-12-10 16:40
Thanks for the diagnostic info, @hirschferkel.

This isn't a Tunnelblick problem; this is all being done by OpenVPN. It's either an OpenVPN problem (which I think is unlikely) or something is blocking the initial handshake to/from the OpenVPN server but allowing subsequent handshakes to get through.

A likely suspect: the security software (OPNSense) which may include a firewall.

**Comment by hirschferkel** [comment] 2023-12-10 16:46
I connect to this OVPN with a server and different mobile setups. None of it suffering any problems. 
It worked without any problems with Tunnelblick untill 3.8.8.

So it strongly seems related to only Tunnelblick.

**Comment by jkbullard** [comment] 2023-12-10 17:05
To repeat: It's all being done by OpenVPN OpenSSL; Tunnelblick itself has nothing to do with it.

If an earlier version of Tunnelblick worked, it would have been because it included a different version of OpenVPN and/or OpenSSL which is behaving differently. However, I have never seen a problem like this caused by OpenVPN or OpenSSL – I have only seen it cause by a hardware or software firewall.

You wrote that Tunnelblick before 3.8.8 worked -- what version was that? (The history shows only that you've used Tunnelblick 3.8.8a and higher.) You could try Tunnelblick 3.8.8b from our [Deprecated Downloads page](https://tunnelblick.net/downloadsDeprecated.html) and see if that works.

**Comment by hirschferkel** [comment] 2023-12-10 18:01
As I wrote it seems related to 3.8.8 so trying any of these releases will fail. 
I used Tunnelblick for years, so rebuilding the OS X my cause the wrong history of Tunnelblick versions.

**Comment by jkbullard** [comment] 2023-12-10 21:49
OpenVPN 2.3.18 is very old and not recommended; it has not been updated for several years. Tunnelblick 4.0.0 does not include it. You should get your OpenVPN provider to update so you can use a newer version.

It could be related to using IPv4 vs. IPv6. Maybe the OpenVPN server isn't responding to IPv6 requests – it must be a very old server since it can only be connected to with such an old version of OpenVPN.

The only way to force IPv4 that I know works is to provide an IPv4 address instead of a domain name in the configuration's "remote" option. However, there might be some way to tell macOS to only use IPv4 addresses or to tell OpenVPN to use only IPv4 addresses when communicating with the server.

**Comment by hirschferkel** [comment] 2023-12-10 21:56
@jkbullard maybe you got my post wrong:  I could connect with 2.5, with no problems, now. I just had to disable IPv6. That's all.

Tunnelblick should have the option to only connect via IPv4. That's all, as it will always try to use IPv6 first and IPv4 on second try.

**Comment by jkbullard** [comment] 2023-12-10 22:12
How did you "disable IPv6"?

**Comment by hirschferkel** [comment] 2023-12-10 22:18
@jkbullard as I wrote: I just disablet the dynamic DNS to forward IPv6. I saw there is an option in the VPN settings of the erver, too, to enable IPv6. But I'm quite nervous about that, as I think of "Never change a running system" and I got into troubles sometimes, to make a small switch in settings of e.g. VPN and not getting back to run it for some time again ...

**Comment by jkbullard** [comment] 2023-12-10 22:24
If there is a way to tell OpenVPN to ignore IPv6 addresses when resolving a domain name for the "remote" option, you could use that. If there isn't, then I don't know a way for Tunnelblick to do it.

I've edited the subject of this thread to better reflect what's going on.

**Closed** 2023-12-10 23:35 UTC
