### ISSUE TITLE
Launch Agent uses deprecated OnDemand key

### ISSUE THREAD

**Issue by rspeed** [Tunnelblick/Tunnelblick#281] opened 2015-11-17 01:15 UTC
The `net.tunnelblick.tunnelblick.LaunchAtLogin` agent uses a key which was deprecated in OS X 10.5. Since the current beta of Tunnelblick only supports 10.5.8 and later and since the deprecated key will likely be removed in some future version of OS X, the file `net.tunnelblick.tunnelblick.LaunchAtLogin.plist` should be updated to use [KeepAlive](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man5/launchd.plist.5.html) instead.

**Comment by rspeed** [comment] 2015-11-17 01:17
Although now that I think of it, it seems like RunAtLoad might be a better option, since you don't actually need to keep the script running.

**Comment by jkbullard** [comment] 2015-11-17 02:13
The next beta will support 10.4 ("Tiger"); only 3.6beta10 didn't support it. There was a bug which as far as I could tell only manifested itself on Tiger. It was difficult to debug because I have no Tiger debugging facilities but – as it turns out – it affected newer versions and the cause was found because of changes to Tunnelblick's threading and event processing. The bug fix will be included in the next beta.

The deprecated key is required on Tiger, and is ignored on later versions of OS X, and the agent works on all systems. (The Console log warning is the only real "problem" with it.)

**Closed by jkbullard** 2015-11-17 02:13 UTC

**Comment by rspeed** [comment] 2015-11-18 19:55
Aah, okay. Is there any way to maybe set this as a todo for when 10.4 support is permanently dropped?

**Comment by jkbullard** [comment] 2015-11-19 02:50
I don't have a formal list of stuff like that, but I have added a comment in the source code about it so when 10.4 support is dropped it will be found when searching for "runningOnLeopardOrNewer()".
