### ISSUE TITLE
"The installation or repair took too long or failed. Try again?" when trying to install a .tblk config file

### ISSUE THREAD

**Issue by sourceblaak** [Tunnelblick/Tunnelblick#775] opened 2023-11-14 06:43 UTC
### When Installing a new .tblk configuration I get the error of "The installation or repair took too long or failed. Try again?"

**additional messages when I run it from terminal with sudo on 3.8.8e:**

"Beginning installation or repair
2023-11-13 02:28:59.227 Tunnelblick[1223:257293] Failed to execute /Applications/Tunnelblick.app/Contents/Resources/installer: (
    1,
    "/var/root/Library/Application Support/Tunnelblick/Configurations/xxxx 5.tblk",
    "/private/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/net.tunnelblick.tunnelblick-7htAwY/xxxx 5.tblk"
)
2023-11-13 02:29:00.712 Tunnelblick[1223:257293] Retrying execution of installer
2023-11-13 02:29:01.205 Tunnelblick[1223:257293] Failed to execute /Applications/Tunnelblick.app/Contents/Resources/installer: (
    0,
    "/var/root/Library/Application Support/Tunnelblick/Configurations/xxxx 5.tblk",
    "/private/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/net.tunnelblick.tunnelblick-7htAwY/xxxx 5.tblk"
)
2023-11-13 02:29:16.540 Tunnelblick[1223:257293] Installation or repair failed; Log:
Tunnelblick installer started 2023-11-13 02:28:59.140936; getuid() = 0; geteuid() = 0; getgid() = 0; getegid() = 0
currentDirectoryPath = '/Users/xxxx'; 3 arguments:
     0x0001
     /var/root/Library/Application Support/Tunnelblick/Configurations/xxxx 5.tblk
     /private/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/net.tunnelblick.tunnelblick-7htAwY/xxxx 5.tblk
Determined username 'xxxx' from current working directory
Apparent symlink attack detected: Symlink is at /var, full path being tested is /var/root/Library/Application Support/Tunnelblick/Configurations/xxxx 5.tblk
Tunnelblick installer failed
Tunnelblick installer started 2023-11-13 02:29:01.102580; getuid() = 0; geteuid() = 0; getgid() = 0; getegid() = 0
currentDirectoryPath = '/Users/xxxx'; 3 arguments:
     0x0000
     /var/root/Library/Application Support/Tunnelblick/Configurations/xxxx 5.tblk
     /private/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/net.tunnelblick.tunnelblick-7htAwY/xxxx 5.tblk
Determined username 'xxxx' from current working directory
Apparent symlink attack detected: Symlink is at /var, full path being tested is /var/root/Library/Application Support/Tunnelblick/Configurations/xxxx 5.tblk
Tunnelblick installer failed
2023-11-13 02:29:16.541 Tunnelblick[1223:257293] Terminating because of error; stack trace: (
	0   Tunnelblick                         0x00000001027fe123 callStack + 67
	1   Tunnelblick                         0x00000001027677c0 -[MenuController terminateBecause:] + 112
	2   Tunnelblick                         0x0000000102775500 -[MenuController runInstaller:extraArguments:usingSystemAuth:installTblks:] + 832
	3   Tunnelblick                         0x00000001027abfbe +[ConfigurationManager copyConfigPath:toPath:usingSystemAuth:warnDialog:moveNotCopy:noAdmin:] + 1134
	4   Tunnelblick                         0x00000001027ad506 -[ConfigurationManager doUninstallslReplacementsInstallsSkipConfirmMsg:skipResultMsg:] + 2662
	5   Tunnelblick                         0x00000001027afa97 -[ConfigurationManager installConfigurations:skipConfirmationMessage:skipResultMessage:notifyDelegate:disallowCommands:] + 4503
	6   Tunnelblick                         0x00000001027afb4f -[ConfigurationManager installConfigurations:skipMessages:notifyDelegate:disallowCommands:] + 143
	7   Tunnelblick                         0x00000001027ba858 +[ConfigurationManager installConfigurationsShowMessagesNotifyDelegateOperation:] + 104
	8   Foundation                          0x00000001060587a2 __NSThread__start__ + 1064
	9   libsystem_pthread.dylib             0x000000010754e109 _pthread_start + 148
	10  libsystem_pthread.dylib             0x0000000107549b8b thread_start + 15
)
2023-11-13 02:29:16.541 Tunnelblick[1223:257293] Could not copy configuration file /private/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/net.tunnelblick.tunnelblick-7htAwY/xxxx 5.tblk to /var/root/Library/Application Support/Tunnelblick/Configurations/xxxx 5.tblk
2023-11-13 02:29:16.545 Tunnelblick[1223:253293] cleanup: Entering cleanup
2023-11-13 02:29:16.549 Tunnelblick[1223:253293] synchronized user defaults
2023-11-13 02:29:16.834 Tunnelblick[1223:253293] Set 'expect disconnect 0 ALL'
2023-11-13 02:29:17.040 Tunnelblick[1223:253293] Finished shutting down Tunnelblick; allowing termination"

**From what I understand it might be because there's a symlink, so it's freaking out. But I have no way to change this because it's in the root of my drive so it's read-only. Furthermore, if I manually copy the .tblk config to Users/user/Libray/Application Support/Tunnelblick/Configurations (without sudo 4.0.0beta11) it says:**

"Tunnelblick[18283:2661016] Beginning installation or repair
2023-11-13 22:35:26.527 Tunnelblick[18283:2661016] /Users/xxxx/Library/Application Support/Tunnelblick/Configurations/xxxx 5.tblk/Contents is owned by root:wheel; needs to be changed to owned by user:80
2023-11-13 22:35:26.527 Tunnelblick[18283:2661016] installer did not make the necessary changes"

**Tunnelblick used to work perfectly, albeit I was on an older version (3.7.7). Ever since updating (I've tried 3.8.8e and 4.0.0beta11) It's been throwing me this issue. Any help greatly appreciated thanks in advance.**

**Comment by jkbullard** [comment] 2023-11-14 11:26
Thanks for your detailed report.

Currently, I am only troubleshooting this problem on Tunnelblick 4.0.0beta11.

I am closing this Issue because it is a duplicate of #773. Please see [my comment there](https://github.com/Tunnelblick/Tunnelblick/issues/773#issuecomment-1809333773).

**Closed by jkbullard** 2023-11-14 11:26 UTC

**Comment by jkbullard** [comment] 2023-11-30 01:54
Tunnelblick 3.8.8f fixes this problem (or these problems).
