### ISSUE TITLE
Can't start a connection with 3.7.7 beta 05

### ISSUE THREAD

**Issue by Ben305** [Tunnelblick/Tunnelblick#486] opened 2018-09-23 10:43 UTC
After updating to 3.7.7 beta 05, I cannot connect or open the settings window any longer. I found this thread: https://groups.google.com/forum/#!topic/tunnelblick-discuss/mW8gBDCyxtk

I'm seeing this in console.app after executing `defaults write net.tunnelblick.tunnelblick DB-SU -bool yes`:

```
Sep 23 12:28:22 MacbookPro Tunnelblick[1041]: Tunnelblick: OS X 10.14.0; Tunnelblick 3.7.7beta05 (build 5130)
Sep 23 12:28:22 MacbookPro Tunnelblick[1041]: DB-SU: init: 004
Sep 23 12:28:22 MacbookPro Tunnelblick[1041]: DB-SU: init: 005
Sep 23 12:28:22 MacbookPro Tunnelblick[1041]: DB-SU: init: 006
Sep 23 12:28:22 MacbookPro Tunnelblick[1041]: DB-SU: init: 006.1
Sep 23 12:28:22 MacbookPro Tunnelblick[1041]: Warning: preferences contain unknown preference 'managmentPortStartingPortNumber'
Sep 23 12:28:22 MacbookPro Tunnelblick[1041]: DB-SU: init: 001
Sep 23 12:28:22 MacbookPro Tunnelblick[1041]: DB-SU: init: 002
Sep 23 12:28:22 MacbookPro Tunnelblick[1041]: DB-SU: init: 003
Sep 23 12:28:22 MacbookPro Tunnelblick[1041]: DB-SU: init: 007
Sep 23 12:28:22 MacbookPro Tunnelblick[1041]: DB-SU: init: 008
Sep 23 12:28:22 MacbookPro Tunnelblick[1041]: DB-SU: init: 009
Sep 23 12:28:22 MacbookPro Tunnelblick[1041]: DB-SU: initialChecks: 001
Sep 23 12:28:22 MacbookPro Tunnelblick[1041]: DB-SU: initialChecks: 002
Sep 23 12:28:22 MacbookPro Tunnelblick[1041]: DB-SU: initialChecks: 003
Sep 23 12:28:22 MacbookPro Tunnelblick[1041]: DB-SU: initialChecks: 004
Sep 23 12:28:22 MacbookPro Tunnelblick[1041]: DB-SU: relaunchIfNecessary: 001
Sep 23 12:28:22 MacbookPro Tunnelblick[1041]: DB-SU: relaunchIfNecessary: 002
Sep 23 12:28:22 MacbookPro Tunnelblick[1041]: DB-SU: initialChecks: 005
Sep 23 12:28:23 MacbookPro Tunnelblick[1041]: DB-SU: initialChecks: 006 - LAST
Sep 23 12:28:23 MacbookPro Tunnelblick[1041]: DB-SU: init: 010
Sep 23 12:28:23 MacbookPro Tunnelblick[1041]: DB-SU: init: 011
Sep 23 12:28:23 MacbookPro Tunnelblick[1041]: DB-SU: init: 012
Sep 23 12:28:23 MacbookPro Tunnelblick[1041]: DB-SU: init: 013
Sep 23 12:28:23 MacbookPro Tunnelblick[1041]: DB-SU: init: 014
Sep 23 12:28:23 MacbookPro Tunnelblick[1041]: DB-SU: init: 015
Sep 23 12:28:23 MacbookPro Tunnelblick[1041]: DB-SU: init: 015.1
Sep 23 12:28:23 MacbookPro Tunnelblick[1041]: DB-SU: init: 016
Sep 23 12:28:23 MacbookPro Tunnelblick[1041]: DB-SU: init: 017
Sep 23 12:28:23 MacbookPro Tunnelblick[1041]: DB-SU: init: 018 - LAST
Sep 23 12:28:23 MacbookPro Tunnelblick[1041]: DB-SU: applicationWillFinishLaunching: 001
Sep 23 12:28:23 MacbookPro Tunnelblick[1041]: DB-SU: applicationDidFinishLaunching: 001
Sep 23 12:28:23 MacbookPro Tunnelblick[1041]: DEPRECATED USE in libdispatch client: dispatch source activated with no event handler set; set a breakpoint on _dispatch_bug_deprecated to debug
Sep 23 12:28:23 MacbookPro Tunnelblick[1041]: DB-SU: applicationDidFinishLaunching: 002
Sep 23 12:28:23 MacbookPro Tunnelblick[1041]: DB-SU: applicationDidFinishLaunching: 003
Sep 23 12:28:23 MacbookPro Tunnelblick[1041]: DB-SU: applicationDidFinishLaunching: 004
Sep 23 12:28:23 MacbookPro Tunnelblick[1041]: DB-SU: applicationDidFinishLaunching: 05
Sep 23 12:28:23 MacbookPro Tunnelblick[1041]: DB-SU: applicationDidFinishLaunching: 06
Sep 23 12:28:23 MacbookPro Tunnelblick[1041]: DB-SU: applicationDidFinishLaunching: 06.2
Sep 23 12:28:23 MacbookPro Tunnelblick[1041]: DB-SU: applicationDidFinishLaunching: 007
Sep 23 12:28:23 MacbookPro Tunnelblick[1041]: DB-SU: applicationDidFinishLaunching: 008
Sep 23 12:28:23 MacbookPro Tunnelblick[1041]: DB-SU: applicationDidFinishLaunching: 009
Sep 23 12:28:23 MacbookPro Tunnelblick[1041]: DB-SU: applicationDidFinishLaunching: 010
Sep 23 12:28:23 MacbookPro Tunnelblick[1041]: DB-SU: applicationDidFinishLaunching: 011
Sep 23 12:28:23 MacbookPro Tunnelblick[1041]: DB-SU: applicationDidFinishLaunching: 012
Sep 23 12:28:23 MacbookPro Tunnelblick[1041]: DB-SU: applicationDidFinishLaunching: 013
Sep 23 12:28:23 MacbookPro Tunnelblick[1041]: DB-SU: applicationDidFinishLaunching: 014
Sep 23 12:28:23 MacbookPro Tunnelblick[1041]: DB-SU: applicationDidFinishLaunching: 015
Sep 23 12:28:23 MacbookPro Tunnelblick[1041]: DB-SU: applicationDidFinishLaunching: 016
Sep 23 12:28:23 MacbookPro Tunnelblick[1041]: DB-SU: applicationDidFinishLaunching: 016.1
Sep 23 12:28:23 MacbookPro Tunnelblick[1041]: DB-SU: applicationDidFinishLaunching: 017
Sep 23 12:28:23 MacbookPro Tunnelblick[1041]: DB-SU: applicationDidFinishLaunching: 018
Sep 23 12:28:23 MacbookPro Tunnelblick[1041]: DB-SU: applicationDidFinishLaunching: 019
Sep 23 12:28:23 MacbookPro Tunnelblick[1041]: DB-SU: applicationDidFinishLaunching: 020
Sep 23 12:28:23 MacbookPro Tunnelblick[1041]: DB-SU: applicationDidFinishLaunching: 021
Sep 23 12:28:23 MacbookPro Tunnelblick[1041]: DB-SU: applicationDidFinishLaunching: 022 -- LAST
Sep 23 12:28:23 MacbookPro Tunnelblick[1041]: Sparkle: ===== Tunnelblick =====
Sep 23 12:28:23 MacbookPro Tunnelblick[1041]: Sparkle: Verified appcast signature
```

However, executing `defaults read net.tunnelblick.tunnelblick | grep 'autoConnect'` returns `exit: 1`

3.7.7 beta 04 and 3.7.6 are working without any problems.

**Comment by jkbullard** [comment] 2018-09-23 12:31
Thanks for your report.

You mention two problems: can't start a connection, and can't open the settings window (by which I assume you mean the "VPN Details" window).

> However, executing defaults read net.tunnelblick.tunnelblick | grep 'autoConnect' returns exit: 1

That's expected if you don't have any configuration(s) set to start when you launch Tunnelblick. That's why you don't have the same problem that was reported at the link you mention (https://groups.google.com/forum/#!topic/tunnelblick-discuss/mW8gBDCyxtk).

The "can't open the settings window" problem may be caused by the "can't start a connection" problem. That is, I think trying to make the connection causes Tunnelblick to  be unable to open the window. (And in the linked post above, trying to make a connection when Tunnelblick was launched caused Tunnelblick to be unable to finish launching.)

Please try the following (without trying to connect):
 1. Quit Tunnelblick if it is running.
 1. Launch Tunnelblick.
 1. Click on the Tunnelblick icon in the menu bar, then click "VPN Details…".

See if you get the "VPN Details" window. If you do, please follow the instructions at [Before You Post](https://tunnelblick.net/cBeforeYouPost.html).

**Comment by Ben305** [comment] 2018-09-23 12:41
@jkbullard I'm unable to open the "VPN Details" window.

**Comment by Ben305** [comment] 2018-09-23 14:07
I'm seeing this in console.app:

```fehler	16:05:00.216778 +0200	Tunnelblick	Received XPC error Connection interrupted for message type 3 kCFNetworkAgentXPCMessageTypePACQuery
fehler	16:05:00.216919 +0200	Tunnelblick	Received XPC error Connection invalid for message type 3 kCFNetworkAgentXPCMessageTypePACQuery
standard	16:05:43.377616 +0200	Tunnelblick	*** Assertion failure in -[_NSToolbarButtonCell setImage:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/AppKit/AppKit-1671/AppKit.subproj/NSButtonCell.m:1534
fehler	16:05:43.377726 +0200	Tunnelblick	Expected NSButton.image to be a kind of NSImage, was null
standard	16:05:43.529299 +0200	Tunnelblick	-[NSNull _fastCStringContents:]: unrecognized selector sent to instance 0x7fff9dedac20
fehler	16:05:43.529537 +0200	Tunnelblick	An uncaught exception was raised
fehler	16:05:43.529588 +0200	Tunnelblick	<private>
fehler	16:05:43.529624 +0200	Tunnelblick	<private>
standard	16:05:43.534753 +0200	Tunnelblick	DB-MO: showStatisticsWindowsTimerHandler: mouse no longer inside a view; NOT queueing showStatisticsWindows
standard	16:05:43.633928 +0200	Tunnelblick	DB-MO: hideStatisticsWindowsTimerHandler: mouse NOT back inside a view; queueing hideStatisticsWindows
```

**Comment by Ben305** [comment] 2018-09-23 21:52
@jkbullard I debugged Tunnelblick and found out that the problem is related to the entry `comp-lzo` in my config which seems to cause the error. 

The exception occurs in line 2106 of VPNConnection.m in the following statement:
```
while (  [[versionToTry substringToIndex: 3] compare: removedInMajorMinor] != NSOrderedAscending  ) {
```

`removedInMajorMinor` is not a string, but NSNull instead.

**Comment by jkbullard** [comment] 2018-09-23 21:54
@Ben305 - Thank you very much. I will look into this later today.

**Comment by jkbullard** [comment] 2018-09-24 14:04
@Ben305 - Thanks for your help.

I have a new version which I believe fixes the bug.

Anyone willing to try it and report back may email developers@tunnelblick.net to get a link to download it.

**Comment by jkbullard** [comment] 2018-09-24 18:15
The new version, 3.7.7beta06, fixes these problems and has been released.

Help from @Ben305 was critical in isolating and resolving the problems.

**Closed by jkbullard** 2018-09-24 18:15 UTC
