### ISSUE TITLE
Systemfolder "/tmp" is not secure under OSX 11 Big Sur 

### ISSUE THREAD

**Issue by F3000** [Tunnelblick/Tunnelblick#636] opened 2020-07-12 19:59 UTC
![Bildschirmfoto 2020-06-24 um 21 50 12](https://user-images.githubusercontent.com/8161283/87255375-87bc0a80-c48a-11ea-8b4f-dbb24d0e4fd2.png)

**Comment by jkbullard** [comment] 2020-07-12 20:46
Duplicate of #632

**Closed by jkbullard** 2020-07-12 20:46 UTC
