### ISSUE TITLE
Asking for pass phrase when there is none defined for the connection

### ISSUE THREAD

**Issue by prjahelka** [Tunnelblick/Tunnelblick#793] opened 2024-03-15 18:26 UTC
Tunnelblick 4.0 and 4.0.1 request a pass phrase. 3.8.8 did not and allows me to connect.

Use a VPN setup that does not have a pass phrase defined.
Upgrade to latest Tunnelblick.
Try to connect, but the app requests a pass phrase.
Cant connect!

Mac OS 14.4 iMac with i9 processor

**Comment by jkbullard** [comment] 2024-03-15 19:11
@prjahelka - Please see [Tunnelblick 4](https://tunnelblick.net/cTunnelblick4.html).

I'm closing this Issue because it seems to be a duplicate of #791.

Feel free to re-open this Issue if you are reporting a bug in Tunnelblick (not an obsolete VPN setup). When doing so, please include the Diagnostic Info after following the procedure in [Read Before You Post](https://tunnelblick.net/cBeforeYouPost.html).

**Closed by jkbullard** 2024-03-15 19:11 UTC
