### ISSUE TITLE
Tunnelblick / OpenVPN hangs after resuming from sleep

### ISSUE THREAD

**Issue by diamondo25** [Tunnelblick/Tunnelblick#659] opened 2020-12-22 10:14 UTC
**Describe the bug**
This issue has been occurring to me a lot of times already. The symptoms are as follows:
1. Menubar icon shows connected, but hovering over it shows beachball
2. Activitymanager shows Tunnelblick (not responding)
3. OpenVPN connection is dead

**To Reproduce**
As this seems to happen on and off, I am not sure what triggers it. It has something to do, I assume, with macOS sleep / losing network connectivity.

**Expected behavior**
When resuming from sleep, Tunnelblick correctly reconnects and doesn't hang.

**Diagnostic information**
This spindump might give you enough information.
[Tunnelblick spindump.txt.zip](https://github.com/Tunnelblick/Tunnelblick/files/5729203/Tunnelblick.spindump.txt.zip)

This chunk also seems to be responsible for the hang (race condition on sleep - wait for DC code?)
```

    +                                         2808 -[MenuController willGoToSleepHandler:]  (in Tunnelblick) + 767  [0x10134b5c4]
    +                                           2797 -[MenuController waitForDisconnection:]  (in Tunnelblick) + 572  [0x10133cedc]
    +                                           ! 2797 usleep  (in libsystem_c.dylib) + 53  [0x7fff6fb09de4]
    +                                           !   2797 nanosleep  (in libsystem_c.dylib) + 196  [0x7fff6fb09eea]
    +                                           !     2796 __semwait_signal  (in libsystem_kernel.dylib) + 10  [0x7fff6fb86756]
    +                                           !     1 cerror  (in libsystem_kernel.dylib) + 20  [0x7fff6fb85241]
    +                                           !       1 cerror_nocancel  (in libsystem_kernel.dylib) + 20  [0x7fff6fb8463d]
    +                                           9 -[MenuController waitForDisconnection:]  (in Tunnelblick) + 388  [0x10133ce24]
    +                                           ! 9 -[VPNConnection noOpenvpnProcess]  (in Tunnelblick) + 58  [0x10132ea94]
    +                                           !   5 -[NSApplication(LoginItem) pIdsForOpenVPNProcessesOnlyMain:]  (in Tunnelblick) + 162  [0x101351f0a]
    +                                           !   : 5 sysctl  (in libsystem_c.dylib) + 171  [0x7fff6fabd86f]
    +                                           !   :   5 __sysctl  (in libsystem_kernel.dylib) + 10  [0x7fff6fb85142]
    +                                           !   4 -[NSApplication(LoginItem) pIdsForOpenVPNProcessesOnlyMain:]  (in Tunnelblick) + 102  [0x101351ece]
    +                                           !     4 sysctl  (in libsystem_c.dylib) + 171  [0x7fff6fabd86f]
    +                                           !       4 __sysctl  (in libsystem_kernel.dylib) + 10  [0x7fff6fb85142]
    +                                           2 -[MenuController waitForDisconnection:]  (in Tunnelblick) + 226  [0x10133cd82]
    +                                             1 __NSArrayM_new  (in CoreFoundation) + 58  [0x7fff35b0b9b3]
    +                                             : 1 __CFAllocateObject  (in CoreFoundation) + 15  [0x7fff35af29bb]
    +                                             :   1 class_createInstance  (in libobjc.A.dylib) + 38  [0x7fff6e88d668]
    +                                             :     1 calloc  (in libsystem_malloc.dylib) + 24  [0x7fff6fbfaed9]
    +                                             :       1 malloc_zone_calloc  (in libsystem_malloc.dylib) + 99  [0x7fff6fbfaf59]
    +                                             :         1 nanov2_calloc  (in libsystem_malloc.dylib) + 81  [0x7fff6fbfb057]
    +                                             :           1 nanov2_allocate  (in libsystem_malloc.dylib) + 367  [0x7fff6fbf9018]
    +                                             :             1 _platform_memset$VARIANT$Haswell  (in libsystem_platform.dylib) + 19  [0x7fff6fc38d73]
    +                                             1 __NSArrayM_new  (in CoreFoundation) + 107  [0x7fff35b0b9e4]
    +                                               1 malloc_good_size  (in libsystem_malloc.dylib) + 21  [0x7fff6fbffee4]

    ```

**Comment by jkbullard** [comment] 2020-12-22 11:06
Try unchecking "Disconnect when computer goes to sleep" on the "Connecting & Disconnecting" tab of Tunnelblick's "Advanced" settings window. Be sure to select the configuration(s) you want the change to apply to on the left side of the "Configuration" panel of Tunnelblick's "VPN Details" window before making the change.

**Comment by diamondo25** [comment] 2020-12-22 11:36
I've changed this setting, but I cannot guarantee that this fixes it (although I think it will). I suppose its best to keep this ticket open as it still locks up for people that do not read github and find the issue?

**Comment by notDavid** [comment] 2021-01-18 19:02
Just an FYI, i'm also experiencing connection issues after waking from sleep (macOS Big Sur.) Will test unchecking "Disconnect when computer goes to sleep"...

**Comment by Aerofluxx** [comment] 2021-04-08 07:05
@notDavid I'm experiencing the same issue with unchecked "Disconnect when computer goes to sleep". 

After waking from a "long" sleep (ie. over night) in macOS Big Sur. Short sleeps are fine, the connection will be stable and can be resumed.

After a "long sleep" it will reconnect fine, but there is no internet available to the system as long as I do not disconnect.

The only way I found is rebooting the Mac every morning.

**Comment by notDavid** [comment] 2021-04-08 07:35
@Aerofluxx I'm seeing the same, the issue mostly happens on battery (and not when the charger is connected) because the Macbook goes into hibernation quicker ("long sleep"). The short sleeps seem to be going fine.

I run this `tunnelblickRestart.sh` script to restart the connection. Also i don't start the tunnelblick *app* at all anymore, because it causes all kinds of trouble and sometimes hangs in some connect/disconnect loop:

```
#!/usr/bin/env sh

echo "Restarting tunnelblick..."
killall Tunnelblick
sleep 1
sudo killall openvpn
sudo launchctl unload /Library/LaunchDaemons/net.tunnelblick.tunnelblick.startup.MyTunnelName.plist
sleep 1
sudo launchctl load -w /Library/LaunchDaemons/net.tunnelblick.tunnelblick.startup.MyTunnelName.plist
sudo killall -HUP mDNSResponder
sleep 5
#open -a /Applications/Tunnelblick.app
echo "Done..."
```

**Comment by GhzTNFj2b19HRNAJBDKSGFYqIctv4** [comment] 2021-11-09 10:22
```
MacBook Pro (Retina, 15-inch, Mid 2014)
macOS BigSur 11.5.2
```

I have a similar issue. When I put my Mac to sleep with VPN connected, the next morning Tunnelblick icon is moving and I have the VPN box asking me to login. I click cancel.

When you try to disconnect the VPN it shows the message: 

```
OpenVPN is not responding to requests to disconnect VPN. Tunnelblick will disconnect when OpenVPN starts responding to disconnection requests. THIS MAY TAKE UP TO TWO MINUTES in certain unusual circumstances. The connection will be unavailable until it is disconnected.
```

Log from tunnelblick:

```
2021-11-08 17:19:49.337325 *Tunnelblick: Established communication with OpenVPN
2021-11-08 18:08:31.850979 *Tunnelblick: Disconnecting because computer is going to sleep
2021-11-08 18:08:33.847263 *Tunnelblick: Expected disconnection occurred.
2021-11-09 08:49:28.746210 *Tunnelblick: Disconnecting; user cancelled authorization
2021-11-09 08:49:29.049551 *Tunnelblick: Disconnecting using 'killall'
2021-11-09 08:49:29.222707 *Tunnelblick: Woke up from sleep. Attempting to re-establish connection...
2021-11-09 09:00:04.819780 *Tunnelblick: Disconnecting; 'Disconnect' (toggle) menu command invoked
2021-11-09 09:00:06.083078 *Tunnelblick: Disconnecting using 'killall'
2021-11-09 09:51:52.428790 *Tunnelblick: Disconnecting; 'Disconnect' (toggle) menu command invoked
2021-11-09 09:51:52.750335 *Tunnelblick: Disconnecting using 'killall'
2021-11-09 09:55:27.970660 *Tunnelblick: Disconnecting; 'Disconnect' (toggle) menu command invoked
2021-11-09 09:55:28.273046 *Tunnelblick: Disconnecting using 'killall'
2021-11-09 09:56:23.300031 *Tunnelblick: Disconnecting; 'Disconnect' (toggle) menu command invoked
2021-11-09 09:56:23.601553 *Tunnelblick: Disconnecting using 'killall'
```

Internet is working fine, there is no VPN subnet in my Mac routing table. I can't SSH to the vpn server.

I have to exit the tunnelblick by clicking Quit Tunnelblick then start again. At this point I get a warning:

```
Warning: Unknown OpenVPN processes
One or more OpenVPN processes are running but are unknown to Tunnelblick. If you are not running OpenVPN separately from Tunnelblick, this usually means that an earlier launch of Tunnelblick was unable to shut them down properly and you should terminate them. They are likely to interfere with Tunnelblick's operation. Do you wish to terminate them?
```

I click terminate at which point I can connect to the VPN.

Logs on the server itself for my user and my IP is from yesterday with nothing from today.

**Comment by tretos53** [comment] 2021-11-09 10:22
```
MacBook Pro (Retina, 15-inch, Mid 2014)
macOS BigSur 11.5.2
```

I have a similar issue. When I put my Mac to sleep with VPN connected, the next morning Tunnelblick icon is moving and I have the VPN box asking me to login. I click cancel.

When you try to disconnect the VPN it shows the message: 

```
OpenVPN is not responding to requests to disconnect VPN. Tunnelblick will disconnect when OpenVPN starts responding to disconnection requests. THIS MAY TAKE UP TO TWO MINUTES in certain unusual circumstances. The connection will be unavailable until it is disconnected.
```

Log from tunnelblick:

```
2021-11-08 17:19:49.337325 *Tunnelblick: Established communication with OpenVPN
2021-11-08 18:08:31.850979 *Tunnelblick: Disconnecting because computer is going to sleep
2021-11-08 18:08:33.847263 *Tunnelblick: Expected disconnection occurred.
2021-11-09 08:49:28.746210 *Tunnelblick: Disconnecting; user cancelled authorization
2021-11-09 08:49:29.049551 *Tunnelblick: Disconnecting using 'killall'
2021-11-09 08:49:29.222707 *Tunnelblick: Woke up from sleep. Attempting to re-establish connection...
2021-11-09 09:00:04.819780 *Tunnelblick: Disconnecting; 'Disconnect' (toggle) menu command invoked
2021-11-09 09:00:06.083078 *Tunnelblick: Disconnecting using 'killall'
2021-11-09 09:51:52.428790 *Tunnelblick: Disconnecting; 'Disconnect' (toggle) menu command invoked
2021-11-09 09:51:52.750335 *Tunnelblick: Disconnecting using 'killall'
2021-11-09 09:55:27.970660 *Tunnelblick: Disconnecting; 'Disconnect' (toggle) menu command invoked
2021-11-09 09:55:28.273046 *Tunnelblick: Disconnecting using 'killall'
2021-11-09 09:56:23.300031 *Tunnelblick: Disconnecting; 'Disconnect' (toggle) menu command invoked
2021-11-09 09:56:23.601553 *Tunnelblick: Disconnecting using 'killall'
```

Internet is working fine, there is no VPN subnet in my Mac routing table. I can't SSH to the vpn server.

I have to exit the tunnelblick by clicking Quit Tunnelblick then start again. At this point I get a warning:

```
Warning: Unknown OpenVPN processes
One or more OpenVPN processes are running but are unknown to Tunnelblick. If you are not running OpenVPN separately from Tunnelblick, this usually means that an earlier launch of Tunnelblick was unable to shut them down properly and you should terminate them. They are likely to interfere with Tunnelblick's operation. Do you wish to terminate them?
```

I click terminate at which point I can connect to the VPN.

Logs on the server itself for my user and my IP is from yesterday with nothing from today.

**Comment by faerietree** [comment] 2022-01-21 18:44
Same for our Apple Mac users. Tunnelblick hangs frequently
@notDavid Can this run without user interaction automatically if VPN connection breaks down / Tunnelblick hangs? cron job overkill likely

**Comment by jkbullard** [comment] 2023-05-06 15:08
This problem may have been fixed in Tunnelblick 4.0.0beta05, released yesterday.
 - It limits the amount of the OpenVPN log that is displayed in the log in the "VPN Details" window. When OpenVPN adds too many entries to the log file too quickly, Tunnelblick displays a note instead of displaying all of the entries.
 - Separately, whenever the OpenVPN log file becomes too large, Tunnelblick truncates (clears) it – see #739.

**Closed** 2023-05-19 21:19 UTC

**Comment by j-rahman** [comment] 2026-03-01 15:28
Why is this issue closed? It still happens to this day. After waking my Mac up from sleep, Tunnelblick gets stuck at the "Connecting..." step. I have to manually click "Disconnect" and then "Connect" again, every single time, to make it connect to the VPN. While doing that Disconnect and Connect workaround, the real IP gets exposed for a brief time, which isn't ideal. Please fix this.

**Comment by jkbullard** [comment] 2026-03-01 16:12
The issue is closed because, for nearly three years, nobody has reported that the fix in Tunnelblick 4.0.0beta05 doesn't work for them.

If you want to re-open it, go ahead, nobody is stopping you. But most problems like this can be fixed by changing settings, for example, what Tunnelblick does on the "Connecting & Disconnecting" tab of the "Advanced" settings window. Be sure to attach a file with (or paste directly into a comment) the info obtained by following the instructions at [Before You Post About a Problem](https://tunnelblick.net/cBeforeYouPost.html)

**Comment by j-rahman** [comment] 2026-03-01 22:01
@jkbullard I do not have permissions to reopen the issue. Anyway, settings are as follows: network access is disabled on expected and unexpected disconnect, and "Disconnect when computer goes to sleep" is turned off.

I suspect the network gets disabled whenever there is a temporary connection issue, but does not get automatically re-enabled when the temporary issue subsides. In the log, I can see something like,
```
Tunnelblick: Could not determine this computer's apparent public IP address before the connection was completed... 
write UDPv4: Network is unreachable (fd=5,code=51)... 
Tunnelblick: Warning: No DNS servers have been specified... 
Inactivity timeout (--ping-restart), restarting... 
SIGUSR1[soft,ping-restart] received, process restarting... 
MANAGEMENT: >STATE:1772401660,RECONNECTING...
```
and then a recurring,
```
Network unreachable, restarting...
Delaying HOLD release for 128.000 seconds...
```
on loop. Selecting "Re-enable Network Access" temporarily leads to a successful reconnection, but then it drops the connection within a couple of seconds, and gets stuck on the reconnecting loop again. Only useful workaround is manually clicking "Disconnect" and then "Connect" again.

**Comment by jkbullard** [comment] 2026-03-01 23:17
Not enough info.

**Comment by j-rahman** [comment] 2026-03-03 15:43
I have attached the log file here: [Tunnelblick.log](https://github.com/user-attachments/files/25720113/Tunnelblick.log). Does this help?

**Comment by jkbullard** [comment] 2026-03-03 16:26
@j-rahman -  Remove or comment out the "persist-tun" line in your OpenVPN configuration file.

**Comment by j-rahman** [comment] 2026-04-07 20:32
> [@j-rahman](https://github.com/j-rahman) - Remove or comment out the "persist-tun" line in your OpenVPN configuration file.

@jkbullard Sorry, I am not sure how to do that. Is that a setting somewhere in the Tunnelblick app? I do not have any separate openvpn installation on my Mac; it must be the one bundled within the Tunnelblick app, and I am not sure where its config files are, if any. Thanks for your help. Much appreciated.

**Comment by jkbullard** [comment] 2026-04-07 23:50
See [Edit or Examine an OpenVPN Configuration File](https://tunnelblick.net/cEditingOpenvpnConfigurationFile.html).

To "comment out' a line, prefix it with a "#" character.

For example, change a line like
     `    persist-tun`
to
    `    #persist-tun`
(That makes it easy to restore: just remove the "#".)
