### ISSUE TITLE
Tunnelblick freezes after sleep

### ISSUE THREAD

**Issue by marinintim** [Tunnelblick/Tunnelblick#355] opened 2017-02-02 10:46 UTC
Hi!
I'm using Tunnelblick on MacOS Sierra.

Sometimes after I wake laptop up from sleep Tunnelblick freezes (in Activity Montitor it's marked as Not responding, when hovering cursor over vpn info window cursor is spinning wheel, etc.).

I have to kill and relaunch Tunnelblick manually in these cases.

I didn't observe this behaviour few updates before.

What additional information I could collect to help debug this issue?

**Comment by jkbullard** [comment] 2017-02-02 10:58
@marinintim - Thanks for your report, and I'm sorry about the problem.

Two questions:
 1. What version of Tunnelblick are you using?
 1. Does this happen only when you have a VPN connected and you sleep/wake your laptop, or does it happen even if no VPN is connected?

**Comment by marinintim** [comment] 2017-02-02 14:11
Tunnelblick 3.7.0beta01 (build 4780)

I run VPN almost all the time, so I'm not sure about your second question, but as far as I remember, only when VPN was connected.

**Comment by jkbullard** [comment] 2017-02-02 14:54
@marinintim - OK, thanks.

The next time this happens, please get "spindump" and "sample" reports for Tunnelblick before you kill and relaunch it. Here are very detailed, click-by-click instructions; the entire process will probably take about five minutes:

 1. Launch the *Activity Monitor* application (it is in /Applications/Utilities).
 1. Click to select the Tunnelblick application in the "Process Name" column (it may help to click on the "Process Name" column heading to sort the list by name).
 1. Click on "View", then "Run Spindump" (it's about half-way down the long list).
 1. (Wait while the Spindump is done; it can take a minute or two.)
 1. Click the "Save" button in the upper-right corner of the Spindump window and save the results to "Spindump.txt" on your Desktop (or somewhere else if you prefer).
 1. Close the Spindump window.
 1. Click on "View", then "Sample Process" (just above "Run Spindump").
 1. (Wait while the sample is taken; it should be faster than the spindump.)
 1. Click the "Save" button in the upper-right corner of the Sample window and save the results to "Sample of Tunnelblick.txt" on your Desktop (or somewhere else if you prefer).
 1. Close the "Sample of Tunnelblick" window.
 1. Quit Activity Monitor.

Then email the two files to developers@tunnelblick.net (so they won't be publicly available).

Thanks again for your report.

**Comment by marinintim** [comment] 2017-02-07 12:45
@jkbullard: Hi! I just've send you an email at this address with Spindump and sample files.

**Comment by jkbullard** [comment] 2017-02-07 13:23
@marinintim - Thanks for your data.

As a temporary workaround for this problem, you can try telling Tunnelblick to _not_ disconnect/reconnect the VPN on sleep/wake:
 1. On the left side of Tunnelblick's "VPN Details" window, select the configuration(s) you want to change.
 2. On the right side, click the "Settings" tab and click the "Advanced" button.
 3. In the new window that appears, click the "Connecting & Disconnecting" tab.
 4. Un-check "Disconnect when computer goes to sleep" and "Reconnect when computer wakes up".

That may or may not work; it depends on your OpenVPN setup.

**Comment by ondrek** [comment] 2017-08-28 15:31
Helped to us as well! Thanks a lot, man! 👍

**Comment by antplus** [comment] 2018-01-27 10:20
Any other updates on this?  I'm running Tunnelblick 3.7.4b (build 4921, OS X 10.7.5+, Intel-64 only) on MacOS Sierra and it pretty much freezes all the time now.  The only way to recover Tunnelblick is to kill it via Activity Monitor.

**Comment by jkbullard** [comment] 2018-01-27 13:00
@antplus - Do the freezes happen even though you have disabled disconnect on sleep?

So far, the developers have only received one Spindump report (for #368, which might be a different problem), which was inconclusive. If more folks sent them that might help.

**Comment by antplus** [comment] 2018-01-27 23:24
@jkbullard  Yes, it's freezing any time there is a "rest" of the network interfaces, currently I'm on the road so I am tethered to my phone.  It hasn't been an issue in the past.  I followed all the previous advice in this thread, but again, any time the sreen saver comes on, machine is idle, or goes to sleep Tunnelblick needs to have "force quit" done.  There are times with packets are still passing, but hovering over the toolbar Tunnelblick icon shows the spinning wheel of death.   Again, the only recovery from that is a force quit.

**Comment by jkbullard** [comment] 2018-01-27 23:45
@antplus - I wonder if OpenVPN is having a problem reconnecting the VPN and hanging (for example, doing a name lookup that is failing). Depending on when that happens, maybe it is catching Tunnelblick off guard or something.

The OpenVPN log and Tunnelblick log are in /Library/Application Support/Tunnelblick/Logs; it might help to see that. (OpenVPN writes its log; Tunnelblick just reads it.) The filenames are long -- they're fiddled-with versions of the full path to the configuration that they're a log of, along with other stuff. But all human-readable, so you should be able to figure out which log is for which configuration. Posting both might help, along with a Spindump.

**Comment by antplus** [comment] 2018-01-27 23:49
Thanks @jkbullard, I'll have a look now.   Is developers@tunnelblick.net  still a good address to submit the files to?

**Comment by jkbullard** [comment] 2018-01-28 00:02
Yes, sending to developers@tunnelblick.net is great. I may reply directly from my personal Gmail account, though; I don't usually send from the tunnelblick.net account.

**Comment by mgrapiniak** [comment] 2018-02-21 15:11
Same issue here:
mac OS Sierra
client version: Tunnelblick 3.7.4b (build 4921)
I will try to get the report and e-mail to you shortly.

**Comment by jkbullard** [comment] 2018-02-21 16:30
Try Tunnelblick 3.7.5beta08, which fixes several problems related to these
freezes. Don't bother to submit reports that aren't from that beta or
higher.

**Comment by DMor1** [comment] 2018-03-12 07:45
I ran into this on `Tunnelblick 3.7.5 (build 5010)`. I wasn't sure if this version is before or after `3.7.5beta08`

**Comment by jkbullard** [comment] 2018-03-12 14:10
@DMor1 - Thanks for your report. 3.7.5beta08 is before 3.7.5. (Betas come before stable releases: 1.2.3beta01, 1.2.3beta02, 1.2.3beta03, … 1.2.3, 1.2.4beta01, 1.2.4beta02, … 1.2.4.) The next time this happens, please get "spindump" and "sample" reports for Tunnelblick. Detailed instructions are in one of my 2/2/2018 posts in this Issue.

**Comment by antplus** [comment] 2018-03-12 22:16
Of 3 macs I own, only one has the freezing issue, they're all running Sierra.  No amount of troubleshooting would fix it, I assume a clean install of Sierra was in order.  I started using the ProtonVPN MacOS beta software on that one so all good.  I'll continue to use Tunnelblick on the other Macs.

**Comment by jkbullard** [comment] 2018-06-29 11:14
Closed because this is fixed in Tunnelblick 3.7.5.

**Closed by jkbullard** 2018-06-29 11:14 UTC

**Comment by andy812** [comment] 2020-05-16 10:46
I use Tunnelblick 3.8.2 (build 5480) and i have the same issue

**Comment by stephlane544** [comment] 2020-12-12 12:57
I'm in 3.8.4 having this issue frequently. Just sent the spindump and sample process files to that email you listed, @jkbullard.

**Comment by jkbullard** [comment] 2020-12-12 13:29
@stephlane544 - Thanks for the data. Have you tried un-checking "Disconnect when computer goes to sleep"? It's on the "Connecting & Disconnecting" tab of the "Advanced" window. Be sure to select the configuration(s) you want it to affect before you un-check the box.

**Comment by albert-a** [comment] 2021-07-15 09:22
The issue is there since I start using Tunelblick. 3-4 years for sure.
Easy to reproduce: just turn off internet connection while the VPN is connected and wait a little.
Sooner you connect the internet - sooner it unfreezes. If you forget to connect internet for a few hours - reboot.
I guess it has something to do with exponential TCP timeouts.

**Comment by jkbullard** [comment] 2021-07-15 12:35
@albert-a - This type of freezing is often a result of Tunnelblick attempting to log the hundreds of thousands of connection attempts per second that OpenVPN does every second in this situation.

You can test that by setting up Tunnelblick to do "No OpenVPN or Tunnelblick logging", and see if the problem happens. (That setting is OK to use because the logging isn't necessary for normal operation of the VPN. It's mostly useful for diagnosing problems.)

If the problem happens even with no logging, it would be helpful to post a "spindump" of Tunnelblick using macOS's "Activity Monitor". Please also include the "Diagnostic Info" produced by a normal connect/disconnect of the VPN using the instructions at [Read Before You Post](https://tunnelblick.net/cBeforeYouPost.html), too.

**Comment by tiptronic85** [comment] 2023-06-28 10:20
It happens also to me, version 3.8.8b.
I remember that last week i checked to ignore a Tunnelblick message, and from that moment i have this problem now.
When i switch on from stop mode, tunnelblick is freezed :(

**Comment by jkbullard** [comment] 2023-06-28 12:59
@tiptronic85 - Try Tunnelblick 4.0.0beta06, which should fix this problem (again).

**Comment by tiptronic85** [comment] 2023-06-28 13:26
> 

I tried to do it yesterday, the installer told me that there are one or many active vpn connections, but Tunnelblick is closed.
How can i bypass this message?

<img width="517" alt="immagine" src="https://github.com/Tunnelblick/Tunnelblick/assets/17149132/62de11a1-39c2-4faa-b0ec-a75d2a341df5">

**Comment by tiptronic85** [comment] 2023-06-28 15:16
Ok i killed them, let's see if it stuck on next STOP.
Thank you

**Comment by Installka** [comment] 2024-06-25 04:07
I have same issue with Tunnelblick 4.0.1 (build 5971) on macOS 14.5

**Comment by albert-a** [comment] 2024-06-25 16:51
> @albert-a - This type of freezing is often a result of Tunnelblick attempting to log the hundreds of thousands of connection attempts per second that OpenVPN does every second in this situation.
> 
> You can test that by setting up Tunnelblick to do "No OpenVPN or Tunnelblick logging", and see if the problem happens. (That setting is OK to use because the logging isn't necessary for normal operation of the VPN. It's mostly useful for diagnosing problems.)
> 
> If the problem happens even with no logging, it would be helpful to post a "spindump" of Tunnelblick using macOS's "Activity Monitor". Please also include the "Diagnostic Info" produced by a normal connect/disconnect of the VPN using the instructions at [Read Before You Post](https://tunnelblick.net/cBeforeYouPost.html), too.

Sorry, I forgot to answer. It actually has nothing to do with logging, the issue is there even when the logs completely disabled. I don't currently have Tunnelblick installed on my macs, but I will consider sending spindump If I have the opportunity.
