### ISSUE TITLE
Can't uninstall it on Big Sur

### ISSUE THREAD

**Issue by i386net** [Tunnelblick/Tunnelblick#653] opened 2020-11-27 10:32 UTC
**Describe the bug**
Trying to uninstall Tunnelblick from OSX Big Sur using Tunnelblick Uninstaller app

**To Reproduce**
1. Open Tunnelblick Uninstaller with CTRL
2. Click Run
3. Click Uninstall

**Diagnostic information**
```
Fri Nov 27 10:18:31 2020 Tunnelblick Uninstaller:
     Uninstalling 'Tunnelblick'
     with bundle ID 'net.tunnelblick.tunnelblick'
     at /Applications/Tunnelblick.app
Secure erase ('rm -P') will not be used to delete files because you are uninstalling from an SSD, and secure erase is not effective on SSDs.
No net.tunnelblick.tunnelblick.plist so not attempting to clear defaults cache for dk
No net.tunnelblick.tunnelblick.plist so not attempting to clear defaults cache for Guest
No net.tunnelblick.tunnelblick.plist so not attempting to clear defaults cache for root
Error: uninstall_tb_user_keychain_items must not be run as root
```

**Comment by jkbullard** [comment] 2020-11-27 14:48
Try giving the Tunnelblick Uninstaller "Full Disk Access" in System Preferences >> Security & Privacy >> Privacy.

**Comment by i386net** [comment] 2020-11-27 14:54
> Try giving the Tunnelblick Uninstaller "Full Disk Access" in System Preferences >> Security & Privacy >> Privacy.

Yes, I've tried that before, but without success.

**Comment by jkbullard** [comment] 2020-11-28 03:15
@i386net wrote
>1. Open Tunnelblick Uninstaller with CTRL
- Can you clarify what you mean by "with CTRL"?

**Comment by i386net** [comment] 2020-11-28 04:30
> * Can you clarify what you mean by "with CTRL"?

I mean, I' m doing as it is written in the manual on the site:
> Control-click the "Uninstaller" and click "Open".

**Comment by jkbullard** [comment] 2020-11-28 15:08
This is a duplicate of #604.

**Closed by jkbullard** 2020-11-28 15:08 UTC
Labels: duplicate
