### ISSUE TITLE
Failed to change owner & group on Tunnelblick.app to match Tunnelblick.app with authorization

### ISSUE THREAD

**Issue by HarryWeppner** [Tunnelblick/Tunnelblick#689] opened 2021-07-01 04:30 UTC
**Describe the bug**
Attempting to update Tunnelblick fails with a message

> Failed to change owner & group on Tunnelblick.app to match Tunnelblick.app with authorization

**To Reproduce**
1. Open Tunnelblick
2. Click on 'Install Update'
3. Click on 'Install and Relaunch'
4. Enter the administrative password
5. Observe error

![Screen Shot 2021-06-30 at 9 25 49 PM](https://user-images.githubusercontent.com/90483/124064581-ed7e0b00-d9e9-11eb-88cd-d8e6cbf70531.png)

**Expected behavior**
I expect Tunnelblick to update.

**Screenshots**

![Screen Shot 2021-06-30 at 9 27 40 PM](https://user-images.githubusercontent.com/90483/124064800-61b8ae80-d9ea-11eb-8c12-5ab512808c70.png)

**Desktop (please complete the following information):**
 - OS: macOS 11.4 (20F71)

**Comment by jkbullard** [comment] 2021-07-01 04:33
Duplicate of #687

**Closed by jkbullard** 2021-07-01 04:33 UTC
