### ISSUE TITLE
Non-Blocking UI

### ISSUE THREAD

**Issue by Bryksin** [Tunnelblick/Tunnelblick#707] opened 2021-11-30 14:49 UTC
When the connection goes down, for example, ethernet cable was unplugged when VPN was active and connected, Tunnelblick attempt to reconnect, which will never happen as network down, or in our VPN we use MFA for the password means previous credentials will never work, in such cases, re-connection will not work out and I need to disconnect and re-connect, but UI gets blocked, once you hover over mouse to click on disconnect button, or left-click on the icon in the status bar to open menu the mouse pointer turns into thinking wheel and application is not responding. 
The only solution is to forcibly terminate it through the Activity monitor (where it also stated that the application is not responding). 

UI should be running in a parallel thread with the main program. Any action related to the network should not block the UI from usage.

**Comment by jkbullard** [comment] 2021-11-30 17:37
The problem is most likely caused by OpenVPN attempting to reconnect in a tight loop without pausing. That sends so much logging info so quickly that Tunnelblick can't keep up processing it.

A solution that might work is to turn off logging. A better solution would be to modify the OpenVPN configuration to not try to reconnect so rapidly. (That would be an OpenVPN setting; I don't know what it is, though.)

**Comment by Bryksin** [comment] 2021-11-30 18:08
Thank you for your response!
I disabled logging and will see how it will go, I will update in the future when disconnect accrue if this problem is still present.

**Comment by jkbullard** [comment] 2023-05-06 15:08
This problem may have been fixed in Tunnelblick 4.0.0beta05, released yesterday.
 - It limits the amount of the OpenVPN log that is displayed in the log in the "VPN Details" window. When OpenVPN adds too many entries to the log file too quickly, Tunnelblick displays a note instead of displaying all of the entries.
 - Separately, whenever the OpenVPN log file becomes too large, Tunnelblick truncates (clears) it – see #739.

**Closed** 2023-05-19 21:19 UTC
