### ISSUE TITLE
Tunnelblick doesn't work anymore with Sonoma 14.2

### ISSUE THREAD

**Issue by pgaufillet** [Tunnelblick/Tunnelblick#782] opened 2023-12-18 09:35 UTC
**Describe the bug**
It seems the latest macos upgrade has broken the way IP address can be assigned to interface. Tunnelblick doesn't work anymore.

**To Reproduce**
1. Connect to your usual openvpn server
2. Network configuration is broken:

```
[...]
2023-12-18 08:51:33.759311 MANAGEMENT: >STATE:1702885893,CONNECTED,SUCCESS,***.***.***.***,***.***.***.***,1194,,
2023-12-18 08:51:33.759426 write UDP: Can't assign requested address (code=49)

```
**Expected behavior**
Revert to the previous behaviour, probably at the cost of a change in the way macos networking APIs are used.

**Desktop (please complete the following information)**
 - OS: Sonoma 14.2 (23C64)
 - Browser: safari 17.2 (19617.1.17.11.9)
 - Version: Tunnelblick 3.8.8e (build 5779.1)

**Comment by jkbullard** [comment] 2023-12-18 13:24
@pgaufillet – please post the diagnostic info obtained by following the instructions at [Read Before You Post](https://tunnelblick.net/cBeforeYouPost.html).

**Comment by pgaufillet** [comment] 2023-12-18 14:02
```
*Tunnelblick: macOS 14.2 (23C64); Tunnelblick 3.8.8e (build 5779.1); prior version 3.8.8d (build 5779); Admin user
git commit bb2553c4a7dd46b90f3018f7d196165655e9e99e + uncommitted changes:
?? ../third_party/sources/IOUserEthernetController.h 
The Tunnelblick.app process is not being translated (x86_64)
System Integrity Protection is enabled
Model: MacBookPro16,1

Configuration openvpn-xxx

"Sanitized" condensed configuration file for /Users/xxx/Library/Application Support/Tunnelblick/Configurations/openvpn-xxx.tblk:

client
nobind
persist-key
persist-tun
auth SHA512
dev tun
fragment 1420
mssfix
proto udp
remote x.y.z.t 1194
remote-cert-tls server
resolv-retry infinite
verb 3
<ca>
[Security-related line(s) omitted]
</ca>
<tls-crypt>
[Security-related line(s) omitted]
</tls-crypt>
<key>
[Security-related line(s) omitted]
</key>
<cert>
[Security-related line(s) omitted]
</cert>


================================================================================

Files in openvpn-xxx.tblk:
      Contents/Resources/config.ovpn

================================================================================

Tunnelblick Kext Policy Data:



================================================================================

Configuration preferences:

-routeAllTrafficThroughVpn = 1
-notOKToCheckThatIPAddressDidNotChangeAfterConnection = 0
-loggingLevel = 3
-lastConnectionSucceeded = 1

================================================================================

Wildcard preferences:


================================================================================

Program preferences:

launchAtNextLogin = 1
tunnelblickVersionHistory = (
    "3.8.8e (build 5779.1)",
    "3.8.8d (build 5779)",
    "3.8.8c (build 5778)",
    "3.8.8b (build 5777)",
    "3.8.8a (build 5776)",
    "3.8.7a (build 5770)"
)
lastLaunchTime = 724578562.402986
lastLanguageAtLaunchWasRTL = 0
connectionWindowDisplayCriteria = showWhenConnecting
maxLogDisplaySize = 102400
lastConnectedDisplayName = openvpn-xxx
keyboardShortcutIndex = 1
updateCheckAutomatically = 1
NSWindow Frame SettingsSheetWindow = 360 150 829 548 0 0 1536 935 
NSWindow Frame ConnectingWindow = 573 538 389 217 0 0 1536 935 
NSWindow Frame SUStatusFrame = 970 122 400 135 0 0 1536 935 
NSWindow Frame SUUpdateAlert = 483 402 620 398 0 0 1536 935 
detailsWindowFrameVersion = 5779.1
detailsWindowFrame = {{334, 309}, {920, 522}}
detailsWindowLeftFrame = {{0, 0}, {167, 402}}
detailsWindowViewIndex = 0
detailsWindowConfigurationsTabIdentifier = settings
leftNavSelectedDisplayName = openvpn-xxx
AdvancedWindowTabIdentifier = sounds
haveDealtWithOldTunTapPreferences = 1
haveDealtWithAlwaysShowLoginWindow = 1
haveDealtWithOldLoginItem = 1
haveDealtWithAfterDisconnect = 1
SUEnableAutomaticChecks = 1
SUScheduledCheckInterval = 86400
SULastCheckTime = 2023-12-18 07:49:25 +0000
SUHasLaunchedBefore = 1

================================================================================

Forced preferences:

(None)

================================================================================

Deployed forced preferences:

(None)

================================================================================

Tunnelblick Log:

2023-12-18 14:38:48.246676 *Tunnelblick: macOS 14.2 (23C64); Tunnelblick 3.8.8e (build 5779.1); prior version 3.8.8d (build 5779)
2023-12-18 14:38:48.702676 *Tunnelblick: Attempting connection with openvpn-xxx using shadow copy; Set nameserver = 769; monitoring connection
2023-12-18 14:38:48.703642 *Tunnelblick: openvpnstart start openvpn-xxx.tblk 61023 769 0 1 0 34652976 -ptADGNWradsgnw 2.5.9-openssl-1.1.1v <password>
2023-12-18 14:38:48.726617 *Tunnelblick: openvpnstart starting OpenVPN
2023-12-18 14:38:49.378298 --cipher is not set. Previous OpenVPN version defaulted to BF-CBC as fallback when cipher negotiation failed in this case. If you need this fallback please add '--data-ciphers-fallback BF-CBC' to your configuration and/or add BF-CBC to --data-ciphers.
2023-12-18 14:38:49.379472 OpenVPN 2.5.9 x86_64-apple-darwin [SSL (OpenSSL)] [LZO] [LZ4] [PKCS11] [MH/RECVDA] [AEAD] built on Oct 23 2023
2023-12-18 14:38:49.379550 library versions: OpenSSL 1.1.1v  1 Aug 2023, LZO 2.10
2023-12-18 14:38:49.380869 MANAGEMENT: TCP Socket listening on [AF_INET]127.0.0.1:61023
2023-12-18 14:38:49.380928 Need hold release from management interface, waiting...
2023-12-18 14:38:49.970736 *Tunnelblick: openvpnstart log:
     OpenVPN started successfully.
     Command used to start OpenVPN (one argument per displayed line):
          /Applications/Tunnelblick.app/Contents/Resources/openvpn/openvpn-2.5.9-openssl-1.1.1v/openvpn
          --daemon
          --log /Library/Application Support/Tunnelblick/Logs/-SUsers-Sxxx-SLibrary-SApplication Support-STunnelblick-SConfigurations-Sopenvpn--xxx.tblk-SContents-SResources-Sconfig.ovpn.769_0_1_0_34652976.61023.openvpn.log
          --cd /Library/Application Support/Tunnelblick/Users/xxx/openvpn-xxx.tblk/Contents/Resources
          --machine-readable-output
          --setenv IV_GUI_VER "net.tunnelblick.tunnelblick 5779.1 3.8.8e (build 5779.1)"
          --verb 3
          --config /Library/Application Support/Tunnelblick/Users/xxx/openvpn-xxx.tblk/Contents/Resources/config.ovpn
          --setenv TUNNELBLICK_CONFIG_FOLDER /Library/Application Support/Tunnelblick/Users/xxx/openvpn-xxx.tblk/Contents/Resources
          --verb 3
          --cd /Library/Application Support/Tunnelblick/Users/xxx/openvpn-xxx.tblk/Contents/Resources
          --management 127.0.0.1 61023 /Library/Application Support/Tunnelblick/Mips/openvpn-xxx.tblk.mip
          --management-query-passwords
          --management-hold
          --redirect-gateway def1
          --script-security 2
          --route-up /Applications/Tunnelblick.app/Contents/Resources/client.up.tunnelblick.sh -9 -d -f -m -w -ptADGNWradsgnw
          --down /Applications/Tunnelblick.app/Contents/Resources/client.down.tunnelblick.sh -9 -d -f -m -w -ptADGNWradsgnw
2023-12-18 14:38:49.981662 MANAGEMENT: Client connected from [AF_INET]127.0.0.1:61023
2023-12-18 14:38:50.018597 MANAGEMENT: CMD 'pid'
2023-12-18 14:38:50.018646 MANAGEMENT: CMD 'auth-retry interact'
2023-12-18 14:38:50.018741 MANAGEMENT: CMD 'state on'
2023-12-18 14:38:50.018847 MANAGEMENT: CMD 'state'
2023-12-18 14:38:50.018900 MANAGEMENT: CMD 'bytecount 1'
2023-12-18 14:38:50.020257 *Tunnelblick: Established communication with OpenVPN
2023-12-18 14:38:50.052604 *Tunnelblick: >INFO:OpenVPN Management Interface Version 3 -- type 'help' for more info
2023-12-18 14:38:50.054422 MANAGEMENT: CMD 'hold release'
2023-12-18 14:38:50.055782 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
2023-12-18 14:38:50.061292 Outgoing Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
2023-12-18 14:38:50.061411 Outgoing Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
2023-12-18 14:38:50.061429 Incoming Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
2023-12-18 14:38:50.061446 Incoming Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
2023-12-18 14:38:50.063030 TCP/UDP: Preserving recently used remote address: [AF_INET]x.y.z.t:1194
2023-12-18 14:38:50.063223 Socket Buffers: R=[786896->786896] S=[9216->9216]
2023-12-18 14:38:50.063264 UDP link local: (not bound)
2023-12-18 14:38:50.063293 UDP link remote: [AF_INET]x.y.z.t:1194
2023-12-18 14:38:50.063623 MANAGEMENT: >STATE:1702906730,WAIT,,,,,,
2023-12-18 14:38:50.129992 MANAGEMENT: >STATE:1702906730,AUTH,,,,,,
2023-12-18 14:38:50.130052 TLS: Initial packet from [AF_INET]x.y.z.t:1194, sid=63aeab0c 1d38e12f
2023-12-18 14:38:50.187383 VERIFY OK: depth=1, C=XX, ST=YYY, L=ZZZ, O=TTT, CN=UUU, emailAddress=x@y
2023-12-18 14:38:50.188555 VERIFY KU OK
2023-12-18 14:38:50.188600 Validating certificate extended key usage
2023-12-18 14:38:50.188620 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
2023-12-18 14:38:50.188637 VERIFY EKU OK
2023-12-18 14:38:50.188653 VERIFY OK: depth=0, C=XX, ST=YYY, L=ZZZ, O=TTT, CN=UUU, emailAddress=x@y
2023-12-18 14:38:50.304215 Control Channel: TLSv1.3, cipher TLSv1.3 TLS_AES_256_GCM_SHA384, peer certificate: 4096 bit RSA, signature: RSA-SHA256
2023-12-18 14:38:50.304333 [xxx] Peer Connection Initiated with [AF_INET]x.y.z.t:1194
2023-12-18 14:38:50.345153 PUSH: Received control message: 'PUSH_REPLY,route a.b.c.d 255.255.255.0,topology net30,ping 10,ping-restart 60,dhcp-option DNS e,f,g,h,dhcp-option DOMAIN lan,ifconfig i,j,k,l i,j,k,l+1,peer-id 4,cipher AES-256-GCM'
2023-12-18 14:38:50.345331 OPTIONS IMPORT: timers and/or timeouts modified
2023-12-18 14:38:50.345356 OPTIONS IMPORT: --ifconfig/up options modified
2023-12-18 14:38:50.345372 OPTIONS IMPORT: route options modified
2023-12-18 14:38:50.345386 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified
2023-12-18 14:38:50.345400 OPTIONS IMPORT: peer-id set
2023-12-18 14:38:50.345413 OPTIONS IMPORT: adjusting link_mtu to 1628
2023-12-18 14:38:50.345427 OPTIONS IMPORT: data channel crypto options modified
2023-12-18 14:38:50.345443 Data Channel: using negotiated cipher 'AES-256-GCM'
2023-12-18 14:38:50.345595 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
2023-12-18 14:38:50.345660 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
2023-12-18 14:38:50.347171 Opened utun device utun6
2023-12-18 14:38:50.347236 MANAGEMENT: >STATE:1702906730,ASSIGN_IP,,i.j.k.l,,,,
2023-12-18 14:38:50.347396 /sbin/ifconfig utun6 delete
                           ifconfig: ioctl (SIOCDIFADDR): Can't assign requested address
2023-12-18 14:38:50.359781 NOTE: Tried to delete pre-existing tun/tap instance -- No Problem if failure
2023-12-18 14:38:50.359824 /sbin/ifconfig utun6 i.j.k.l+1 i.j.k.l mtu 1500 netmask 255.255.255.255 up
2023-12-18 14:38:50.364515 /sbin/route add -net x.y.z.t o.p.q.r 255.255.255.255
                           add net x.y.z.t: gateway o.p.q.r
2023-12-18 14:38:50.370210 /sbin/route add -net 0.0.0.0 i.j.k.l 128.0.0.0
                           add net 0.0.0.0: gateway i.j.k.l
2023-12-18 14:38:50.374324 /sbin/route add -net 128.0.0.0 i.j.k.l 128.0.0.0
                           add net 128.0.0.0: gateway i.j.k.l
2023-12-18 14:38:50.378074 MANAGEMENT: >STATE:1702906730,ADD_ROUTES,,,,,,
                           14:38:50 *Tunnelblick:  **********************************************
                           14:38:50 *Tunnelblick:  Start of output from client.up.tunnelblick.sh
                           14:38:53 *Tunnelblick:  Disabled IPv6 for 'Wi-Fi'
                           14:38:53 *Tunnelblick:  Retrieved from OpenVPN: name server(s) [ X.Y.Z.T ], domain name [ lan ], search domain(s) [ ], and SMB server(s) [ ]
                           14:38:53 *Tunnelblick:  Not aggregating ServerAddresses because running on macOS 10.6 or higher
                           14:38:53 *Tunnelblick:  Setting search domains to 'lan' because the search domains were not set manually (or are allowed to be changed) and 'Prepend domain name to search domains' was not selected
                           14:38:55 *Tunnelblick:  Saved the DNS and SMB configurations so they can be restored
                           14:38:55 *Tunnelblick:  Changed DNS ServerAddresses setting from '' to 'X.Y.Z.T'
                           14:38:55 *Tunnelblick:  Changed DNS SearchDomains setting from '' to 'lan'
                           14:38:55 *Tunnelblick:  Changed DNS DomainName setting from '' to 'lan'
                           14:38:55 *Tunnelblick:  Did not change SMB NetBIOSName setting of ''
                           14:38:55 *Tunnelblick:  Did not change SMB Workgroup setting of ''
                           14:38:55 *Tunnelblick:  Did not change SMB WINSAddresses setting of ''
                           14:38:55 *Tunnelblick:  DNS servers 'X.Y.Z.T' will be used for DNS queries when the VPN is active
                           14:38:55 *Tunnelblick:  NOTE: The DNS servers do not include any free public DNS servers known to Tunnelblick. This may cause DNS queries to fail or be intercepted or falsified even if they are directed through the VPN. Specify only known public DNS servers or DNS servers located on the VPN network to avoid such problems.
                           14:38:55 *Tunnelblick:  Flushed the DNS cache via dscacheutil
                           14:38:55 *Tunnelblick:  /usr/sbin/discoveryutil not present. Not flushing the DNS cache via discoveryutil
                           14:38:55 *Tunnelblick:  Notified mDNSResponder that the DNS cache was flushed
                           14:38:55 *Tunnelblick:  Not notifying mDNSResponderHelper that the DNS cache was flushed because it is not running
                           14:38:55 *Tunnelblick:  Setting up to monitor system configuration with process-network-changes
                           14:38:55 *Tunnelblick:  End of output from client.up.tunnelblick.sh
                           14:38:55 *Tunnelblick:  **********************************************
2023-12-18 14:38:55.256084 Initialization Sequence Completed
2023-12-18 14:38:55.256146 MANAGEMENT: >STATE:1702906735,CONNECTED,SUCCESS,i.j.k.l,x.y.z.t,1194,,
2023-12-18 14:38:55.256279 write UDP: Can't assign requested address (code=49)
2023-12-18 14:38:55.256415 write UDP: Can't assign requested address (code=49)
2023-12-18 14:38:56.361632 *Tunnelblick: Warning: No DNS servers have been specified.
2023-12-18 14:39:05.565191 write UDP: Can't assign requested address (code=49)
2023-12-18 14:39:15.099208 *Tunnelblick: Disconnecting; VPN Details… window disconnect button pressed

================================================================================

Down log:

14:39:15 *Tunnelblick:  **********************************************
14:39:15 *Tunnelblick:  Start of output from client.down.tunnelblick.sh
14:39:15 *Tunnelblick:  Cancelled monitoring system configuration changes
14:39:15 *Tunnelblick:  Removed State:DNS
14:39:15 *Tunnelblick:  Removed Setup:DNS
14:39:15 *Tunnelblick:  Removed State:SMB
14:39:15 *Tunnelblick:  Restored DNS and SMB settings
14:39:15 *Tunnelblick:  Re-enabled IPv6 (automatic) for "Wi-Fi"
14:39:16 *Tunnelblick:  Flushed the DNS cache with dscacheutil -flushcache
14:39:16 *Tunnelblick:  Notified mDNSResponder that the DNS cache was flushed
14:39:16 *Tunnelblick:  End of output from client.down.tunnelblick.sh
14:39:16 *Tunnelblick:  **********************************************

================================================================================

Previous down log:

10:37:47 *Tunnelblick:  **********************************************
10:37:47 *Tunnelblick:  Start of output from client.down.tunnelblick.sh
10:37:47 *Tunnelblick:  Cancelled monitoring system configuration changes
10:37:47 *Tunnelblick:  Removed State:DNS
10:37:47 *Tunnelblick:  Removed Setup:DNS
10:37:47 *Tunnelblick:  Removed State:SMB
10:37:47 *Tunnelblick:  Restored DNS and SMB settings
10:37:47 *Tunnelblick:  Re-enabled IPv6 (automatic) for "Wi-Fi"
10:37:47 *Tunnelblick:  Flushed the DNS cache with dscacheutil -flushcache
10:37:47 *Tunnelblick:  Notified mDNSResponder that the DNS cache was flushed
10:37:47 *Tunnelblick:  End of output from client.down.tunnelblick.sh
10:37:47 *Tunnelblick:  **********************************************

================================================================================

Network services:

An asterisk (*) denotes that a network service is disabled.
Wi-Fi

Wi-Fi Power (en0): On

================================================================================

ifconfig output:

lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> mtu 16384
	options=1203<RXCSUM,TXCSUM,TXSTATUS,SW_TIMESTAMP>
	inet 127.0.0.1 netmask 0xff000000
	inet6 ::1 prefixlen 128 
	inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1 
	nd6 options=201<PERFORMNUD,DAD>
en0: flags=88e3<UP,BROADCAST,SMART,RUNNING,NOARP,SIMPLEX,MULTICAST> mtu 1500 constrained
	options=6460<TSO4,TSO6,CHANNEL_IO,PARTIAL_CSUM,ZEROINVERT_CSUM>
	ether 3c:22:fb:88:87:3f
	inet6 fe80::cf6:6e91:544e:13f7%en0 prefixlen 64 secured scopeid 0x6 
	inet6 2a01:cb01:306c:f165:4d2:a544:61ba:e391 prefixlen 64 autoconf secured 
	inet6 2a01:cb01:306c:f165:c028:27e6:8cd0:222d prefixlen 64 autoconf temporary 
	inet 192.0.0.2 netmask 0xffffffff broadcast 192.0.0.2
	inet6 2a01:cb01:306c:f165:18d2:231d:ecd9:83a prefixlen 64 clat46
	nat64 prefix 64:ff9b:: prefixlen 96
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect
	status: active
utun0: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1500
	inet6 fe80::3f00:4588:d456:aacb%utun0 prefixlen 64 scopeid 0xe 
	nd6 options=201<PERFORMNUD,DAD>
utun1: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1380
	inet6 fe80::2d42:5698:eb7d:fb4b%utun1 prefixlen 64 scopeid 0xf 
	nd6 options=201<PERFORMNUD,DAD>
utun2: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 2000
	inet6 fe80::8061:7e9c:f168:6393%utun2 prefixlen 64 scopeid 0x10 
	nd6 options=201<PERFORMNUD,DAD>
utun3: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1000
	inet6 fe80::ce81:b1c:bd2c:69e%utun3 prefixlen 64 scopeid 0x11 
	nd6 options=201<PERFORMNUD,DAD>
utun4: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1380
	inet6 fe80::ee0:df50:d6ed:a766%utun4 prefixlen 64 scopeid 0x12 
	nd6 options=201<PERFORMNUD,DAD>
utun5: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1380
	inet6 fe80::d1f0:c3ef:1a8f:799d%utun5 prefixlen 64 scopeid 0x13 
	nd6 options=201<PERFORMNUD,DAD>

================================================================================

Non-Apple kexts that are loaded:

Index Refs Address            Size       Wired      Name (Version) UUID <Linked Against>

================================================================================

Quit Log:

2023-12-18 00:15:15.995392 applicationShouldTerminate: termination because of shutdown; delayed until 'shutdownTunnelblick' finishes)
2023-12-18 00:15:15.998521 shutDownTunnelblick: started.
2023-12-18 00:15:15.999458 shutDownTunnelblick: Starting cleanup.
2023-12-18 00:15:16.001497 cleanup: Entering cleanup
2023-12-18 00:15:16.002573 synchronized user defaults
2023-12-18 00:15:17.023718 Set up flag files for shutting down the computer and expecting all configurations to be disconnected
2023-12-18 00:15:17.025316 doDisconnectionsForShuttingDownComputer: Set 'expect disconnect 1 ALL'
2023-12-18 00:15:17.028077 Started disconnecting all configurations
2023-12-18 00:15:17.029560 Skipping cleanup because computer is shutting down or restarting
2023-12-18 00:15:17.030369 shutDownTunnelblick: Cleanup finished.
2023-12-18 00:15:17.031597 Finished shutting down Tunnelblick; allowing termination

================================================================================

Traces Log:


================================================================================

Console Log:

```

**Comment by pgaufillet** [comment] 2023-12-18 14:03
Here is the log. I had to anonymize it, as far as I could.

**Comment by jkbullard** [comment] 2023-12-18 15:36
@pgaufillet - see if restarting the computer fixes the problem.

**Comment by pgaufillet** [comment] 2023-12-19 09:06
Test performed, without change in the behaviour: 

`2023-12-19 10:03:06.763987 write UDP: Can't assign requested address (code=49)`

**Comment by jkbullard** [comment] 2023-12-19 12:18
Hundreds  of thousands of connections are being made successfully every day with macOS 14.2, so there is probably something about the OpenVPN setup or your computer's setup that's causing the problem.

The less common options that your configuration includes are `nobind`, `mssfix`, and `fragment 1420`. You can try removing them one at a time to see if that helps.

Otherwise, you should consult OpenVPN experts. See our [Support page](https://tunnelblick.net/support.html) for some links.

**Comment by pgaufillet** [comment] 2023-12-20 08:19
I don't think so: this configuration is running for years without any issue and it is clearly a local rights problem.
I am going to investigate and will post to this thread once the root cause found.

Thank you for your support.

**Comment by pgaufillet** [comment] 2023-12-20 10:05
I think I have finally found something. 
The Tunnelblick option "Disable ipv6 unless the VPN server uses an ipv6 adddress." is usually enabled in my configuration.
Disabling it solves the issue. Reenabling it causes it again. This behaviour has changed with the upgrade to Sonoma 14.2.

**Comment by pgaufillet** [comment] 2023-12-20 10:08
FWIW: IPv6 is disabled on the server side.

**Comment by sajallimbu** [comment] 2024-01-12 04:55
Same issue on my end. I get
`2024-01-12 10:26:01.559886 /sbin/ifconfig utun4 delete ifconfig: ioctl (SIOCDIFADDR): Can't assign requested address`
error on Tunnelblick log. I can connect to the VPN but the traffic is not being routed through it. I tried converting the tap to tun as well on both server and client but the issue is still there. I even disabled "Disable ipv6 unless the VPN server uses an ipv6 adddress." but not working.

**Comment by jkbullard** [comment] 2024-01-12 16:24
@sajallimbu, please post the diagnostic info obtained by following the instructions at [Read Before You Post](https://tunnelblick.net/cBeforeYouPost.html).

**Comment by jkbullard** [comment] 2024-01-28 15:23
I'm closing this issue: the original poster's problem was fixed, and @sajallimbu has not reponded to a request for the diagnostic info.

**Closed by jkbullard** 2024-01-28 15:23 UTC
