### ISSUE TITLE
Tunnelblick 3.7.9beta05 (build 5240) can not load kext on 10.14.5 Beta (18F108f)

### ISSUE THREAD

**Issue by Weuxel** [Tunnelblick/Tunnelblick#527] opened 2019-04-11 11:24 UTC
When trying to connect to a network on latest Beta (10.14.5 Beta (18F108f)) of Mojave, this error occurs:

Could not start OpenVPN (openvpnstart returned with status #247)

Contents of the openvpnstart log:
openvpnstart log:
     Loading tap-signed.kext
     stderr from kextload: /Applications/Tunnelblick.app/Contents/Resources/tap-signed.kext failed to load - (libkern/kext) system policy prevents loading; check the system/kernel logs for errors or try kextutil(8).
     stderr from kextload: /Applications/Tunnelblick.app/Contents/Resources/tap-signed.kext failed to load - (libkern/kext) system policy prevents loading; check the system/kernel logs for errors or try kextutil(8).
     stderr from kextload: /Applications/Tunnelblick.app/Contents/Resources/tap-signed.kext failed to load - (libkern/kext) system policy prevents loading; check the system/kernel logs for errors or try kextutil(8).
     stderr from kextload: /Applications/Tunnelblick.app/Contents/Resources/tap-signed.kext failed to load - (libkern/kext) system policy prevents loading; check the system/kernel logs for errors or try kextutil(8).
     stderr from kextload: /Applications/Tunnelblick.app/Contents/Resources/tap-signed.kext failed to load - (libkern/kext) system policy prevents loading; check the system/kernel logs for errors or try kextutil(8).
     Unable to load net.tunnelblick.tun and/or net.tunnelblick.tap kexts in 5 tries. Status = 27

**Comment by jkbullard** [comment] 2019-04-11 20:00
@Weuxel - Thanks for reporting this.

Can anyone confirm that Tunnelblick 3.7.9beta04 can successfully load the Tap kext? Or some even earlier version of Tunnelblick?

Once I know that, I will give a detailed response to this report.

**Comment by jkbullard** [comment] 2019-04-12 00:01
@Weuxel (and anyone else) – I have an new version of Tunnelblick that I believe will fix this Issue.

I'd like it tested by others before I release it.

Email developers@tunnelblick.net to get a link to download it.

**Comment by Weuxel** [comment] 2019-04-12 04:03
@jkbullard Nice, mail is sent.

**Comment by jkbullard** [comment] 2019-04-12 09:57
I wrote:
>  I have an new version of Tunnelblick that I believe will fix this Issue.

Unfortunately, testing has shown that it doesn't fix this Issue.

But I encourage anyone who can test yet another version to email developers@tunnelblick.net an offer to test the next new version for this problem. It might be available today, but is more likely to be available at the end of next week.

**Comment by jkbullard** [comment] 2019-04-12 10:53
Please see [Problems Loading Kexts on macOS 10.14.5](https://tunnelblick.net/cKextNotarization.html) for a description of the cause of the problem and possible workarounds and solutions.

**Comment by jkbullard** [comment] 2019-04-13 02:16
I've updated [Problems Loading Kexts on macOS 10.14.5](https://tunnelblick.net/cKextNotarization.html).

**Comment by Weuxel** [comment] 2019-04-18 05:43
As a Workaround downgrading to Tunnelblick 3.7.8 works for me.

**Comment by jkbullard** [comment] 2019-04-18 12:11
Thanks, @Weuxel - Was yours an upgrade to 10.14.5 Beta 2, or a clean install of 10.14.5 Beta 2?

My understanding of Apple's very vague description is that a "clean install" would not let Tunnelblick 3.7.8 load it kexts, but that an upgrade to 10.14.5 would let Tunnelblick 3.7.8 load its kexts. If that's not correct, I'd appreciate hearing about it.

Downgrading to a previous version of Tunnelblick which had successfully loaded the kext(s) should work on an update to 10.14.5 Beta 2 (or, presumably 10.14.5 when it is released), as described in [Problems Loading Kexts on macOS 10.14.5.](https://tunnelblick.net/cKextNotarization.html).

**Comment by Weuxel** [comment] 2019-04-18 12:25
Hello,
yes it was an upgraded 10.14.5 Beta 2.
I did that because of what you wrote on the linked page.
Just thought i gave that feedback.

**Comment by jkbullard** [comment] 2019-04-25 23:42
This problem is fixed in Tunnelblick 3.7.9beta06 for macOS 10.14.5 Beta 3 (and, I hope and expect, for macOS 10.14.5).

A combination of a change from Beta 2 to Beta 3 of macOS and including "old" kexts (old builds; the source code hasn't changed for years) in Tunnelblick 3.7.9beta06 solves this problem. See newly-updated [Problems Loading Kexts on macOS 10.14.5 Beta 2](https://tunnelblick.net/cKextNotarization.html) for details.

**Comment by jkbullard** [comment] 2019-04-25 23:43
And thanks again, @Weuxel, for reporting this and helping refine a fix.

**Comment by Weuxel** [comment] 2019-04-26 07:57
Thanks, works like a charm.

**Comment by jkbullard** [comment] 2019-04-29 22:51
Closed. Tunnelblick 3.7.9beta06 fixes this problem.

**Closed by jkbullard** 2019-04-29 22:51 UTC
