### ISSUE TITLE
Tunnelblick.net is down?

### ISSUE THREAD

**Issue by NcuIT** [Tunnelblick/Tunnelblick#425] opened 2018-01-11 17:33 UTC
Tunnelblick.net is down.  
<img width="1269" alt="screen shot 2018-01-11 at 11 33 32 am" src="https://user-images.githubusercontent.com/28809870/34838336-4e67ea8e-f6c3-11e7-8eaa-9124e5fd6c0a.png">

**Comment by jkbullard** [comment] 2018-01-11 17:47
Duplicate of #424.

**Closed by jkbullard** 2018-01-11 17:47 UTC
